### ISSUE TITLE
Issues using material-table with redux

### ISSUE THREAD

**Issue by whuey1992** [mbrn/material-table#1014]
When I use redux to handle the data that is being passed to material-table. I run into this error
"Invariant Violation: A state mutation was detected between dispatches, in the path `user.data.0.tableData`. This may cause incorrect behavior". It seems that material-table is doing some kind of state change when my dispatches are occurring. Only solution I have found so far is creating a clone of the data in redux like this data={JSON.Parse(JSON.Stringify(this.props.data))

**Comment by v1siuol** [comment]
Same issue when I tried to re-render. 
Originally my code: 
```
const { posts } = props;

// ... In render 
data={ posts }
```

I FIX it by 
```
const _posts = props.posts || []
const posts = _posts.map(item => {
  const im = { ...item }
  return im;
});

// ... In render 
data={ posts }
```

**Comment by xgarrett** [comment]
Hello,
I've figured out same issue in our project.

Temporary fixed by deep cloning of `data` before it's passed to `material-table`.

@mbrn could you please take a look on that?

For me it looks like a serious bug that some kind of internal state from library is appended to data being passed to a component.
If `material-table` needs to have its own copy of data with extra params it should do it internally.
