### ISSUE TITLE
Editable column with a function returns type error

### ISSUE THREAD

**Issue by malekjaroslav** [mbrn/material-table#1183]
When I add custom editable function like this: 
```
editable: (_, { type }) => {
  return type !== AgeRangeType.Infant
}
```
It works, but return an error in the console: 
<img width="811" alt="Screenshot 2019-10-12 at 13 51 53" src="https://user-images.githubusercontent.com/7753942/66696628-d2d89f80-ecf7-11e9-84ab-ace0722c1e7d.png">

**Comment by Domino987** [comment]
Yes because editable can only be one of 'always' 'never' 'onUpdate' or 'onAdd'. What are you trying to achieve?

**Comment by malekjaroslav** [comment]
I need to make the column editable based on the data it contains. This is actually working and it is correct by the typescript definition, it only throws an error...

**Comment by upschmidtcreek** [comment]
I get this error as well.  My function works and the render is what I want, but I get this type error.

**Current PropTypes:** 
editable: PropTypes.oneOf(['always', 'onUpdate', 'onAdd', 'never', PropTypes.func]),

Looking at the PropType specs "oneOf" is an enum checker and expects values.  PropTypes.func is a method.

PropTypes.oneOfType expects an array of methods, so that may work.  I don't have time to check the below, but this might be an option.

editable: PropTypes.oneOfType([PropTypes.oneOf(['always', 'onUpdate', 'onAdd', 'never']), PropTypes.func])

**Comment by upschmidtcreek** [comment]
Didn't notice commit 4ebfc14 until now.  Thanks for the fix!

**Comment by jackHedaya** [comment]
Still have this error in `1.51.4`. Will this be corrected in a future version?

**Comment by apjavier2** [comment]
> Yes because editable can only be one of 'always' 'never' 'onUpdate' or 'onAdd'. What are you trying to achieve?

Thanks for this. Fixed my code as well :)
