### ISSUE TITLE
Material-Table , Grouping with the counter

### ISSUE THREAD

**Issue by ramyam07** [mbrn/material-table#1210]
In material-table  can we show the  count with grouping

**Comment by ramyam07** [comment]
https://stackoverflow.com/questions/58419151/reactjs-material-table-grouping-with-the-counter-1210-react-material-table

**Comment by RidhwanDev** [comment]
Did you manage to figure out how to do this?

**Comment by jroyleaz** [comment]
You could maintain your own counter and then map it back to the values for `columns.title`. It's not perfect or ideal, necessarily, but it works. Basically you'll want to:

**Create a Counter Map**
Use your `data` array to create a map that counts instances of a particular column (ie, data property that correlates to `columns.field`). Something like:

```javascript

const tableData = [
  {
    name: 'John Smith',
    city: 'Dallas',
    state: 'Texas',
  },
  {
    name: 'Steve Smith',
    city: 'Plano',
    state: 'Texas',
  },
  {
    name: 'Mark Smith',
    city: 'Dallas',
    state: 'Texas',
  },
  {
    name: 'Sally Smith',
    city: 'Austin',
    state: 'Texas',
  },
  {
    name: 'Becky Smith',
    city: 'Plano',
    state: 'Texas',
  },
  {
    name: 'Julie Smith',
    city: 'Dallas',
    state: 'Texas',
  },
];

const getCountsByField = (data, fieldName) =>
  data.reduce((counts, { [fieldName]: field }) => {
    if (!counts[field]) counts[field] = 1;
    else counts[field]++;
    return counts;
  }, {});

const cityCounts = getCountsByField(tableData, 'city');

// cityCounts: { Austin: 1, Dallas: 3, Plano: 2 }
```

**Update Your Data**
Somewhere in your code, after fetching your data and after building the above map:

```javascript
const countedData = tableData => tableData.map(row => {
  const label = cityCounts[row.city] <= 1 ? 'city' : 'cities';
  return {
    ...row,
    city: `${row.city} - ${cityCounts[row.city]} ${label}`,
  }
});
```

And then pass that into Material Table. You could probably get clever with `padStart()` to get a little bit of formatting if you put the counts on the left side of the field value.  I hope that helps, because unfortunately you can't use `render()` with grouping. I'm not sure why, since they could still just group by the `field` value. 🤷‍♂️ 

Disclaimer: This is all just rough, off-the-cuff code. It may need to be tweaked/cleaned-up to suit your needs.

**Comment by georgii-sirotkin** [comment]
It was answered on stack overflow https://stackoverflow.com/a/58812904/5719097
