### ISSUE TITLE
Editable Input File exits editing mode after selecting file

### ISSUE THREAD

**Issue by meiXXue** [mbrn/material-table#1285]
I was wondering if there's any solution to avoid clicking the edit button again to submit the file. Any help would be appreciated. Thanks!
<img width="893" alt="Screen Shot 2019-11-03 at 2 37 39 AM" src="https://user-images.githubusercontent.com/50377267/68081881-15673680-fde3-11e9-9e88-b55646df9716.png">
<img width="650" alt="Screen Shot 2019-11-03 at 2 37 53 AM" src="https://user-images.githubusercontent.com/50377267/68081882-1730fa00-fde3-11e9-89e5-b93688628b4e.png">

```
{
        title: "Photo",
        field: "photo",
        editable: 'always',
        editComponent: () => (
          <div value="photo">
            <input
              accept="image/*"
              style={{ display: 'none' }}
              id="raised-button-file"
              multiple
              type="file"
              onChange={onFileChange}
            />
            <label htmlFor="raised-button-file">
              <Button variant="raised" component="span">
                Upload
              </Button>
            </label>
          </div>
        ),
        render: rowData =>
          rowData.photo === undefined ?
            (
              <Image src="http://lorempixels.com/1600/900/nature/"></Image>
            )
            :
            (
              <Image src={rowData.photo} aspectRatio={16 / 9} />
            )
      }
```

**Comment by M-tarek93** [comment]
I assume that you are using useState() to keep the file changes in a state. This would make the component re-render whenever you change the file since the state has changed which leads to exiting the edit mode while keeping the chosen file in the state.
I recommend using useRef instead of useState since useRef will store the file value changes without re-rendering

for the component:
`chosenImage = React.useRef(null)`

the input element:
`....`
`// Replace onChange`
` // onChange={onFileChange}`
`// with ref`
`ref={ chosenImage }`
`....`

Then you can use the files array using:
`chosenImage.current.files`

If it's a single file use the first element of the array
`chosenImage.current.files[0]`

**Comment by hatchli** [comment]
@M-tarek93 Thank you for your insight! I sucesfully implemented  image and multiple image upload columns using dropzone. However, because I can't set state to trigger a disabled prop or set a loading state (when uploading), the user receives 0 visual feedback as to the success or progress of an upload... I can't even prevent them from submitting the form mid-upload.

Do you have any advice or strategy to address this by chance? 

Thanks

**Comment by hatchli** [comment]
Bump

**Comment by JeffreyOdogba** [comment]
> @M-tarek93 Thank you for your insight! I sucesfully implemented image and multiple image upload columns using dropzone, replacing state and useState with useRef. However, because I can't set state to trigger a disabled prop or set a loading state (when uploading), the user receives 0 visual feedback as to the success or progress of an upload... I can't even prevent them from submitting the form mid-upload.
> 
> Do you have any advice or strategy to address this by chance?
> 
> Thanks
> 
> ```
> {
>       title: "Gallery",
>       field: "gallery",
>       render: (props) => {
>         return props.gallery.map((image, i) => (
>           <img
>             key={i}
>             src={image.url}
>             style={{ width: "50px", height: "auto" }}
>           />
>         ));
>       },
>       editComponent: (props) => {
>         return (
>           <>
>             <Uploader
>               // disabled={images.current.length>0}
>               files={files.current}
>               onDrop={onDrop}
>               multiple={true}
>             />
>           </>
>         );
>       },
>     },
> ```

This was very helpful. How was the file included in the table data, My file is showing up.

**Comment by redamsy** [comment]
i have the same issue, i am using editComponent and inside i have a file input,  onChange i am sending http request, which leads to exiting the edit mode , can anyone help?? urgent

**Comment by redamsy** [comment]
i have the same issue, i am using editComponent and inside i have a component which sends http request, this leads to exiting the edit mode , can anyone help?? urgent

**Comment by AmrViernes** [comment]
Hey Guys the solution for this is to assign a let variable and store what you want in this variable while editing and it will work like a charm on the edit mode.
