### ISSUE TITLE
Warning: Failed prop type: Invalid prop `detailPanel` supplied to `MaterialTable`. 

### ISSUE THREAD

**Issue by lfsando** [mbrn/material-table#1387]
Started happening in version 1.54.1

**Warning**
<img width="523" alt="detailPanelWarning" src="https://user-images.githubusercontent.com/10608706/69656147-c82f5b00-1056-11ea-9962-cb7eff4be384.png">

**Code**
<img width="872" alt="detailPanelCode" src="https://user-images.githubusercontent.com/10608706/69656148-c82f5b00-1056-11ea-911a-a3e1d6972297.png">

`<TelephoneDetails />` is just a div with a `<p>` tag.

**Comment by mageshkumar1598** [comment]
Am also having the same issue but in different Icon(Add).

**Comment by brunojkurt** [comment]
found a solution for this warning in my case, maybe the source of your warning its not the same

Since the warning is throwed by some object validation i started to removing items hoping the warning goes away to find the issue, and realize that when i removed the icon prop, the warning was gone, so i took a look in the docs again and saw the problem:

I was declaring the icon prop in the wrong way:
![wrong](https://user-images.githubusercontent.com/31192708/73538176-0d7e5900-4409-11ea-9ca1-882c30ce209e.PNG)

Right way:
![right](https://user-images.githubusercontent.com/31192708/73538189-153dfd80-4409-11ea-8569-c9936fe62804.PNG)
