### ISSUE TITLE
problem if during editing i click something else

### ISSUE THREAD

**Issue by vash-trigun** [mbrn/material-table#1446]
I noticed that when i click on edit button to change the values of a row, if i decide to click another button instead of check or cancel button (to confirm or cancel the edit of the row).... all the rows of the table become faded like when i click the edit button of a row

**Comment by SETA-thanhnt** [comment]
I have the same bug as yours. Have you fixed it?

**Comment by vash-trigun** [comment]
@SETA-thanhnt , hi.... i'm sorry... still looking for a fix.
For the moment i prefered to use another table component for my project. Luckily i was at the beginning

**Comment by aaronlna** [comment]
Stumbled upon this earlier this week... looked through the code and capturing what I found:

MaterialTable captures [a boolean state called `hasAnyEditingRow`](https://github.com/mbrn/material-table/blob/6edd2f5e5af64535e46309aff947590e116180bf/src/material-table.js#L595). This boolean is derived from whether or not its internal **DataManager** has saved a reference to a `lastEditingRow` (this reference is assigned when you begin editing).

When you are editing, `lastEditingRow` gets assigned AND a flag for whether or not to show the edit row [is stored *on* the row data itself via **DataManager**](https://github.com/mbrn/material-table/blob/6edd2f5e5af64535e46309aff947590e116180bf/src/utils/data-manager.js#L181) (the data is under the `tableData` field of the row data object).  Now the problem exists when you update the data your table is displaying, this editing flag is lost because new data is replacing your current rows. The reference to `lastEditingRow` (and subsequently `hasAnyEditingRow`) remains... hence you're left with a table that's in editing mode (grayed out rows), but no associable row to show as being edited.

I'm not sure what the design choice was for capturing the edit state as a field of the row data itself (rather than a regular React Component state). Any time theres a data change to the table there's necessary state that's being directly overwritten.

Some workarounds for this are to modify DataManager to preserve editing state across updates to the table data , or simply have MaterialTable or DataManager drop the `hasAnyEditingRow`/`lastEditingRow` state/assignment when updates to row data come in. Of course there's also the consideration of capturing this state outside of the row data altogether which would avoid this issue, but may produce other complexities.
