### ISSUE TITLE
The Filter on A Filtered Column Stops Working After Dragging Column to Different Order Then Re-Filter

### ISSUE THREAD

**Issue by ShevaShen** [mbrn/material-table#1461]
**Describe the bug**
If the table has at least one column filter set, then try to re-order the columns by dragging the head cell, the filter on the column will stop working after filtering twice.

I am at `1.54.2`, I used `onFilterChange` to log out the filter. It seems the `column.field` will change.

**To Reproduce**
1. Go to the online demo https://material-table.com/#/docs/features/filtering
2. Click on 'Basic Filtering Example'
3. Filter the last column 'Birth Place', select 'istanbul'
4. Drag the column to the very first
5. Once the 'Birth Place' is the first column, unselect 'istanbul', then select 'istanbul' again
6. Drag the 'Birth Place' to the second column, try to unselect 'istanbul', it stops working afterwards

**Expected behavior**
The filters should still working no matter how many times a user drag and filter that column.

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version 79.0.3945.79 (Official Build) (64-bit)

**Comment by max-graaab** [comment]
is this solved?

**Comment by giq-re** [comment]
It works after the first drag and then breaks.  Meaning the filter stays on the the previous column.  I’m not sure where the state is being held for the column order but I know that onorderchange is using the original column ordering as inserted because I had to save that state so that could ensure that after remote data changes that the current sort would be honored.
