### ISSUE TITLE
Case insensitive default sort

### ISSUE THREAD

**Issue by r-s-sandbox** [mbrn/material-table#1497]
**Is your feature request related to a problem? Please describe.**
https://codesandbox.io/s/material-demo-0i09t
In the codesandbox example, default sorting is case sensitive on the name column so ahmet appears at bottom rather than top. It would be ideal to make default sorting configurable through a prop.

**Describe the solution you'd like**
A boolean prop to enable/disable case sensitive default sort

**Describe alternatives you've considered**
I considered custom sort but that requires user interaction once table is rendered. I would like the column pre-sorted upon render. I got it to work with default sorting after introducing toUpperCase() in the else block of sort function in data-manager.js

**Comment by thepetas** [comment]
Hi, do you plan to add this feature in the near future ?

**Comment by fridaystreet** [comment]
+1

**Comment by jeffsupancic** [comment]
Easily solved through a `customSort` function, but would be nice to have an option for case insensitivity.

**Comment by fridaystreet** [comment]
Yeah we've solved it through custom sort function, but I guess what most
would expect or believe to be the standard/default wouldn't be capitalised
sorting. Rather than having to boiler plate every column / table with a
custom sort function.

I don't think I've ever seen a table sort that even does capitalised sort,
let alone is the default.

But hey, it's not my library so who am I to judge
