### ISSUE TITLE
Edit mode is not canceled when component unmounts

### ISSUE THREAD

**Issue by miktap** [mbrn/material-table#1562]
**Describe the bug**
If a component is unmounted while a row is being edited, the edit mode is not properly canceled. If you mount the component again you can see that the row stays in edit mode. However the other rows are not disabled so one can start editing two rows simultaneously. 

**To Reproduce**
1. Start editing a row
2. Unmount the component (change the view or something...)
3. Mount the component again (go back)
4. The previously edited row is still in edit mode

**Expected behavior**
Editing is canceled when component unmounts.

**Additional context**
Workaround is to use `material-table` internal API call when component unmounts:

```typescript
import React, { createRef } from 'react';

export default function Demo() {
  const tableRef = createRef();

  React.useEffect(() => {
    return () => {
      (tableRef?.current as any)?.dataManager?.changeRowEditing();
    }
  }, [tableRef])

  return (
        <MaterialTable
          tableRef={tableRef}
          ...
}
```

**Comment by javierbrea** [comment]
The problem happens because `material-table` add properties to the provided data, storing some "states", as in the case of  the `detailPanel` state.

If you are returning always the same reference in the `data` callback (an usual scenario if you are caching or memoizing the results), then it will remain modified, and when the `material-table` is mounted again, it will recover the "state".

Cloning the data before passing them to `material-table` fixed the issue in my case.
