### ISSUE TITLE
in edit phase everything become grey

### ISSUE THREAD

**Issue by vash-trigun** [mbrn/material-table#1610]
**Describe the bug**
in edit phase all the rows become grey

**To Reproduce**
1. click the pencil to edit a row
2. during this phase the other rows become grey, so click something else outside the table (for example another button), instead of the save or cancel button.
3. See error: now all the rows become grey also the row that were on edit phase

**Expected behavior**
the row choosed should stay on edit phase or at least automatic cancel the edit phase so all the rows return like how they were at the beginning

**Additional context**
i notice that during the edit phase if you click other buttons a part the save and cancel button, the material table component forget which row was on edit phase.
for example during the edit phase you can still use the search textfield

**Comment by aaronlna** [comment]
Stumbled upon this earlier this week... looked through the code and capturing what I found:

MaterialTable captures [a boolean state called `hasAnyEditingRow`](https://github.com/mbrn/material-table/blob/6edd2f5e5af64535e46309aff947590e116180bf/src/material-table.js#L595). This boolean is derived from whether or not its internal **DataManager** has saved a reference to a `lastEditingRow` (this reference is assigned when you begin editing).

When you are editing, `lastEditingRow` gets assigned AND a flag for whether or not to show the edit row [is stored *on* the row data itself via **DataManager**](https://github.com/mbrn/material-table/blob/6edd2f5e5af64535e46309aff947590e116180bf/src/utils/data-manager.js#L181) (the data is under the `tableData` field of the row data object).  Now the problem exists when you update the data your table is displaying, this editing flag is lost because new data is replacing your current rows. The reference to `lastEditingRow` (and subsequently `hasAnyEditingRow`) remains... hence you're left with a table that's in editing mode (grayed out rows), but no associable row to show as being edited.

I'm not sure what the design choice was for capturing the edit state as a field of the row data itself (rather than a regular React Component state). Any time theres a data change to the table there's necessary state that's being directly overwritten.

Some workarounds for this are to modify DataManager to preserve editing state across updates to the table data , or simply have MaterialTable or DataManager drop the `hasAnyEditingRow`/`lastEditingRow` state/assignment when updates to row data come in. Of course there's also the consideration of capturing this state outside of the row data altogether which would avoid this issue, but may produce other complexities.

**Comment by aaronlna** [comment]
Forgot to post this. There's a temporary workaround while this bug exists. You can access `dataManager` via the MaterialTable `tableRef` property and manually change row editing yourself. I'm just clearing the edit state whenever MT gets a new set of data to render:

```js
const tableRef: RefObject = createRef();

// Call this whenever you need editing to be reset
if (tableRef.current) tableRef.current.dataManager.changeRowEditing();

// Render
<MaterialTable tableRef={this.tableRef} />
```

**Comment by vash-trigun** [comment]
Thx a lot man... i will try it ;)

**Comment by vash-trigun** [comment]
> Forgot to post this. There's a temporary workaround while this bug exists. You can access `dataManager` via the MaterialTable `tableRef` property and manually change row editing yourself. I'm just clearing the edit state whenever MT gets a new set of data to render:
> 
> ```js
> const tableRef: RefObject = createRef();
> 
> // Call this whenever you need editing to be reset
> if (tableRef.current) tableRef.current.dataManager.changeRowEditing();
> 
> // Render
> <MaterialTable tableRef={this.tableRef} />
> ```

I have a problem with this declaration:
const tableRef: RefObject = createRef();

i am using javascript and look like RefObject is typescript code.
and i don't understand where i should declare it, if inside the constructor() or outside the class component

**Comment by vash-trigun** [comment]
after i did some experiment i changed the if with this;
if (this.tableRef.current && (this.tableRef.current.state.lastEditingRow || this.tableRef.current.state.showAddRow)) {
            this.tableRef.current.dataManager.changeRowEditing();
    }

because lastEditingRow and showAddRow are what initialize hasAnyEditingRow in material-table.
But still not sure of leave this if in render() phase.

**Comment by yurivangeffen** [comment]
I have a similar issue, when calling 
```typescript
tableRef.current.dataManager.changeRowEditing(someRowData, 'update')
```
All rows grey out. Naturally I can't call `changeRowEditing()`, as I want to go into edit mode on a specific row.

**Comment by thedmeyer** [comment]
What about the opposite? I want to be able to put multiple rows in edit mode at the same time.

**Comment by aaronlna** [comment]
> What about the opposite? I want to be able to put multiple rows in edit mode at the same time.

I would submit a new feature request for this. This would require some changes to at least DataManager and perhaps some of the table components using it for rendering. As long as it requires DataManager changes I don't think this is easily doable through the pre-existing API (referring to component overriding).

**Comment by aaronlna** [comment]
This issue can be closed.
