### ISSUE TITLE
Editable Delete Tooltip should say "Delete" not "Save"

### ISSUE THREAD

**Issue by hariria** [mbrn/material-table#1698]
**Describe the bug**
on your example, when I delete a row, it asks to confirm (✓ or x) and the tooltip for the delete icon confirmation says "save" not "delete". This is very confusing for users. This is clearly shown in your own documentation for material table. Link here: [Material UI Editable Example](https://material-table.com/#/docs/features/editable)

**To Reproduce**
1. Go to [material ui editable example](https://material-table.com/#/docs/features/editable)
2. Click the dropdown for 'Editable Example'
3. click delete
4. notice that the tooltip for confirming delete says "Save" not "Delete"

**Expected behavior**
Should be "delete" for tooltip text on delete, not "save"

**Comment by hariria** [comment]
@mbrn is there anyone that can help me with this

**Comment by Androsv96** [comment]
You can modify this tooltips as you want inside localization prop given to the MaterialTable. 
About confirm delete tooltip I think it is because they share the same string. I think they way you can solve this is through a ternary checking if the user is editing or deleting, based on that you can give to localization prop a different value.
Example: 
```javascript
 <MaterialTable 
     localization={ {body: isUserDeleting? value : otherValue}}
/>
```
where value could be 
```javascript
{cancelTooltip: "cancel", saveTooltip: "Delete" }
```
and otherValue could be
```javascript
{cancelTooltip: "cancel", saveTooltip: "Save" }
```
I don't know if this is the better solution for this but it could help you out meanwhile.

**Comment by excardis** [comment]
Hi,  saw this post and I was troubling for the similar question too, found the solution like below:
          localization={{
            body: {
               deleteTooltip: 'Remove Address',
               editRow : {
                               saveTooltip :'Delete'
                              },
                    }
           }}
