### ISSUE TITLE
setState onClick function only triggers once on custom header

### ISSUE THREAD

**Issue by JordanSh** [mbrn/material-table#1731]
[CodeSandBox](https://codesandbox.io/s/material-table-testing-actions-position-and-output-2-6umzj
)
I've built a custom header with an onClick function that should change a simple boolean state, it seems to only trigger once.

check the sandbox to see the problem, click on the custom header a few times to see that the state change happens only once on the first click.

 - OS: MAC OSX
 - All browsers

When i tried to set the columns without a state it worked fine. but that's not the intended functionality i need. my columns will arrive from an api so they must be inside a state.

**Comment by Androsv96** [comment]
Hello there.
As far I can see there is something weird with the setIsOpen(!isOpen) inside your memoizedCallback function because it does execute each time you click on the header but it doesn't change the state. 
If you console(!isOpen) you will see that it changes from false to true at the first time, but then it returns true all the time, meaning that the isOpen state didn't change so nothing happens.
So I will suggest to get rid of the memoizedCallback function and put your setIsOpen(!isOpen) inside the onOrderChange callback, cause anyway both memoizedCallback and orderFunc are being executed when you click on the header.

**Comment by JordanSh** [comment]
ok thats an option to consider. thanks!

**Comment by Domino987** [comment]
Can you close this issue, if it is resolved? Thanks
