### ISSUE TITLE
defaultFilter: false not working

### ISSUE THREAD

**Issue by radzk** [mbrn/material-table#1749]
**Describe the bug**
Setting defaultFilter to false is not working

**To Reproduce**
Have a boolean flag in the data.
Define a column for that boolean.
Set defaultFilter to false, because you want to initially hide rows with this boolean set as false.

**Expected behavior**
It filters the data.

**Additional context**
Setting defaultFilter as true works correctly.

**Comment by oze4** [comment]
Can you supply some code or a demo of this?

**Comment by radzk** [comment]
Just tried to prepare some code...
```
<MaterialTable
         columns={[
                        {
                            title: "Name",
                            field: "name",
                        },
                        {
                            title: "Value",
                            defaultFilter: true,
                            type: 'boolean',
                            field: "value"
                        },
                    ]}
                    options={{
                        filtering: true,
                    }}
                    data={[
                        {
                            name: 'name1',
                            value: true
                        },
                        {
                            name: 'name2',
                            value: false
                        }
                    ]}
                />
```
and actually it behaves even differently than what I experienced before.... this example, as far as I understand, should display me only a row `name1` because I set the `defaultFilter` to be same as `name1`'s `value`. Switching the `defaultFilter` to `false` should occur in displaying only the second row. Can you confirm or help me to achieve it? Thanks!

**Comment by oze4** [comment]
So it looks like there are some inconsistencies with boolean columns in general, as [this issue](https://github.com/mbrn/material-table/issues/947) outlines.

In order to filter a boolean column, you do not use `true` or `false`, rather `'checked'` (true), `'unchecked'` (false), or `undefined` (indeterminate) - see [this bit of source code](https://github.com/mbrn/material-table/blob/master/src/components/m-table-filter-row.js#L64-L71) for more info.

Therefore, in order to get this to work properly, use the following filter:

### [You can view a live demo here](https://stackblitz.com/edit/react-epqw8n?embed=1&file=AppTable.js)

<img width="513" alt="image" src="https://user-images.githubusercontent.com/21092343/77258549-4688bc00-6c49-11ea-9b30-f761ed595538.png">


```javascript
import React from "react";
import MaterialTable from "material-table";
import tableIcons from "./TableIcons.js";

export default function AppTable() {
  return (
    <MaterialTable
      icons={tableIcons}
      columns={[
        {
          title: "Name",
          field: "name"
        },
        {
          title: "Value",
          defaultFilter: "checked", // 'checked', 'unchecked', or undefined
          type: "boolean",
          field: "value"
        }
      ]}
      options={{
        filtering: true
      }}
      data={[
        {
          name: "name1",
          value: true
        },
        {
          name: "name2",
          value: false
        }
      ]}
    />
  );
}
```
</details>

**Comment by radzk** [comment]
Perfect!! This is what I needed, thank you very much 👍 Would be cool to update the docs for it.

**Comment by oze4** [comment]
@radzk I agree - docs seem to be missing a lot that would help with a ton of open issues.. crazy that I had to dig into source code to find that answer.
