### ISSUE TITLE
Detail panel does not stay open

### ISSUE THREAD

**Issue by brummelte** [mbrn/material-table#1841]
**Describe the bug**
I am using a resize observer that uses setState to set width and height on component size change. If I open the detail panel, the resize observer fires and sets the new height. Then the detail panel is removed again immediately.

**To Reproduce**
You can reproduce it as well if you set a state in the onClick of the expansion icon.
https://codesandbox.io/s/flamboyant-lewin-uzb7e?file=/src/App.js

**Expected behavior**
Expansion panel should open.

**Screenshots**
![animation](https://user-images.githubusercontent.com/7269775/79558215-198ec400-80a4-11ea-88bc-374455abf53c.gif)

**Comment by brummelte** [comment]
I've found out that every parent state change removes the detail panel.

**Comment by brummelte** [comment]
Memoizing the data seems to prevent this bug until the data changes again.

But the expansion panel should survive a new data array.

**Comment by victoraduarte** [comment]
I have the same issue with the detail panel not staying open. In my case, when I click the detail panel I need to fetch remote server data to show in my custom component that is rendered via the detail panel. The async call updates my redux state which appears to cause a re-render which closes the detail panel. It looks like the panel is never opened but in the debugger I can see the panel with the remote data but when I let the debugger run past the breakpoints, the detail panel disappears. I even tried having the custom component fetch the data, which still updates the redux state, and have the same issue. Any thoughts on a workaround? It would be extremely useful to be able to issue a remote call and have the data reflected in the detail panel. 

OnRowAdd and OnRowUpdate work perfectly because they are wrapped in a promise. For those, I'm able to fetch remote data and retain the underlying row panel open.

Thanks for any suggestions. Great table!!!
