### ISSUE TITLE
Demo Doesn't Work

### ISSUE THREAD

**Issue by bishonen** [mbrn/material-table#1858]
**Describe the bug**
Trying to do npm run for the demo, does not work out of the box

**To Reproduce**
1. Download the library and try to run npm start
2. Open browser and see error in the console

**Expected behavior**
The demo page should load

**Additional context**
Error below:

```
m-table-filter-row.js:177 Uncaught TypeError: Cannot read property 'icons' of undefined
    at MTableFilterRow.eval [as renderDefaultFilter] (m-table-filter-row.js:177)
    at MTableFilterRow.getComponentForColumn (m-table-filter-row.js:235)
    at eval (m-table-filter-row.js:252)
    at Array.map (<anonymous>)
    at MTableFilterRow.render (m-table-filter-row.js:248)
    at finishClassComponent (react-dom.development.js:17160)
    at updateClassComponent (react-dom.development.js:17110)
    at beginWork (react-dom.development.js:18620)
    at HTMLUnknownElement.callCallback (react-dom.development.js:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:237)
```

**QuickFix**
Comment out the following line to get it working again:

https://github.com/mbrn/material-table/blob/master/demo/demo.js#L118

**Comment by oze4** [comment]
I am also getting an errors when trying to run the demo ***or*** build the project.  

The fix you mentioned (commenting out the `filtering` prop) does resolve this for me ***BUT*** I was also getting a different error, which I was able to resolve as well.

<details>
<summary>
<b>Click me to view all of the errors I am receiving:</b> (it is worth noting that I incorporated an error boundary component in my testing)
</summary>

<p>
<code>
The above error occurred in the <MTableFilterRow> component:
in MTableFilterRow (created by MTableBody)
in tbody (created by ForwardRef(TableBody))
in ForwardRef(TableBody) (created by WithStyles(ForwardRef(TableBody)))
in WithStyles(ForwardRef(TableBody)) (created by MTableBody)
in MTableBody (created by Droppable)
in table (created by ForwardRef(Table))
in ForwardRef(Table) (created by WithStyles(ForwardRef(Table)))
in WithStyles(ForwardRef(Table)) (created by Droppable)
in div (created by Droppable)
in div (created by Droppable)
in div (created by Droppable)
in Droppable (created by ConnectFunction)
in ConnectFunction
in ConnectFunction (created by MaterialTable)
in div
in Unknown (created by WithStyles(Component))
in WithStyles(Component) (created by MaterialTable)
in div (created by ForwardRef(Paper))
in ForwardRef(Paper) (created by WithStyles(ForwardRef(Paper)))
in WithStyles(ForwardRef(Paper)) (created by Container)
in Container (created by MaterialTable)
in Provider (created by App)
in App (created by ErrorBoundary)
in ErrorBoundary (created by DragDropContext)
in DragDropContext (created by MaterialTable)
in MaterialTable
in Unknown (created by WithStyles(Component))
in WithStyles(Component) (created by App)
in div (created by App)
in App
in ErrorBoundary

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary. react-dom.development.js:19527:13
The above error occurred in the <ErrorBoundary> component:
in ErrorBoundary (created by DragDropContext)
in DragDropContext (created by MaterialTable)
in MaterialTable
in Unknown (created by WithStyles(Component))
in WithStyles(Component) (created by App)
in div (created by App)
in App
in ErrorBoundary

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary. react-dom.development.js:19527:13
The above error occurred in the <MaterialTable> component:
in MaterialTable
in Unknown (created by WithStyles(Component))
in WithStyles(Component) (created by App)
in div (created by App)
in App
in ErrorBoundary

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary. react-dom.development.js:19527:13
TypeError: _this2.props is undefined 2 bundle.js line 8972 > eval:178:1
TypeError: this.tableContainerDiv.current is null bundle.js line 9080 > eval:571:9
</code>
</p>
</details>

### This is how I fixed all errors:

In my troubleshooting, I noticed [this recent commit](https://github.com/mbrn/material-table/blob/a7ee2d4a88749a17a649e7b0570e4cd08c902564/src/material-table.js#L55) contains some changes that cause one of the errors I am getting...  If I change that to the following, the error about `this.tableContainerDiv.current is null bundle.js line 9080 > eval:571:9` goes away.

```javascript
// Fix for this.tableContainerDiv.current is null bundle.js line 9080 > eval:571:9
  componentDidMount() {
    this.setState({ 
        ...this.dataManager.getRenderState(), 
        width: this.tableContainerDiv.current && this.tableContainerDiv.current.scrollWidth }, () => {
      if (this.isRemoteData()) {
        this.onQueryChange(this.state.query);
      }
    });
  }
```

As far as the main error, which goes away when you comment out `filtering` (as you pointed out), I am still trying to determine if that is a Webpack issue or a Material Table issue..  At first I thought [that this commit](https://github.com/mbrn/material-table/blob/70a41c2d1a7a8aa53ae64765dbb45892609f5a97/src/components/m-table-filter-row.js#L85) may have caused the error, but even when I comment that out, I still get an error.. 

What I have discovered is that the root cause for this error has to do with scoping of `this`.. I was able to resolve this error by changing [this block (this line in particular](https://github.com/mbrn/material-table/blob/master/src/components/m-table-filter-row.js#L94) to: 

```javascript
renderDefaultFilter = (columnDef) => {
  const localization = { ...MTableFilterRow.defaultProps.localization, ...this.props.localization };

  /* This was added to correct the scoping issue */
  const self = this;
  /* ^^^^^^^^^^^^^ */

  return (
    <TextField
      style={columnDef.type === 'numeric' ? { float: 'right' } : {}}
      type={columnDef.type === 'numeric' ? 'number' : 'search'}
      value={columnDef.tableData.filterValue || ''}
      placeholder={columnDef.filterPlaceholder || ''}
      onChange={(event) => {
        this.props.onFilterChanged(columnDef.tableData.id, event.target.value);
      }}
      InputProps={this.props.hideFilterIcons || columnDef.hideFilterIcon ? undefined : {
        startAdornment: (
          <InputAdornment position="start">
            <Tooltip title={localization.filterTooltip}>

              {/* Using `self` here resolved the issue */}
              <self.props.icons.Filter />
              {/* ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ */}

            </Tooltip>
          </InputAdornment>
        )
      }}
    />
  );
}
```
I honesty have no clue why that worked... This component has been using `<this.props.icons.Filter />` for the longest time (I reviewed the history of `m-table-filter-row.js`).. So any ideas on why this would randomly start to happen would be awesome!

After making these changes, I was able to run the demo and build the project.

**Comment by watchsteve** [comment]
I got this same exact bug in my own code using the lastest version of material-table. I downgraded to 1.57.0 and it fixed the issue.

`import React from 'react';
import { daysUntil } from '../../helper';

// @ts-ignore
import MaterialTable, {MTableToolbar} from 'material-table'
import { makeStyles } from '@material-ui/core/styles';

import Container from '@material-ui/core/Container';
import Icon from '@material-ui/core/Icon';
import blue from '@material-ui/core/colors/blue';


const useStyles = makeStyles(theme => ({
  Current: {
    backgroundColor: "#5cb85c",
    padding: ".2em .6em .3em",
    color: "white",
  },
  Notify: {
    backgroundColor: "#f0ad4e",
    padding: ".2em .6em .3em",
    color: "white",
  },
  Expired: {
    backgroundColor: "#d9534f",
    padding: ".2em .6em .3em",
    color: "white",
  },
}));


const issueList = ( props ) => {

  const classes = useStyles();

  const colorState = (rowData) => {
    return(
      <span className={classes[rowData.certification_state]}>
        {rowData.certification_state}
      </span>
    )
  }

  const formatDate = (dates) => {
    let date = new Date(dates);

    let year = date.getFullYear();
    let month = date.getMonth()+1;
    let dt = date.getDate();

    if (dt < 10) {
      dt = '0' + dt;
    }
    if (month < 10) {
      month = '0' + month;
    }

    return (
      <span>{(month+ '-' + dt + '-' + year)}</span>
    )
  }

  const title = props.title;

  const quickActionHandler = props.quickActionHandler;

  return (
    <Container maxWidth='xl'>

      <div className="IssuePg">
        <div className="row">
          <div className="col text-left">
          </div>
        </div>
        <div className="row pt-3">
          <div className="col">
            <MaterialTable
              columns={[
                // { title: 'Id', field: 'trackingobj_id', filtering: false},
                { 
                  title: 'Building', 
                  field: 'building.street_and_nums',
                  render: rowData => <a href={`/buildings/${rowData.building_id}`} style={{color: 'blue'}}>{rowData.building.street_and_nums}</a>

                },
                { 
                  title: 'Tracking Item', 
                  field: 'name',
                  render: rowData => <a href={`/issues/${rowData.trackingobj_id}`} style={{color: 'blue'}}>{rowData.name}</a>

                },
                { 
                  title: 'Category', 
                  field: 'category.name',
                  render: rowData => <a href={`/categories/${rowData.category_id}`} style={{color: 'blue'}}>{rowData.category.name}</a>

                },
                { 
                  title: 'Certification Status', 
                  field: 'certification_state',
                  render: (rowData) => colorState(rowData),
                  lookup: {
                    // 'Current': (() =>  {return(
                    //   <span className={classes.Current}> Current </span>
                    //  ) } )(),
                    // 'Notify': (() =>  {return(
                    //   <span className={classes.Notify}> Notify </span>
                    //  ) } )(),
                    // 'Expired': (() =>  {return(
                    //   <span className={classes.Expired}> Expired </span>
                    //  ) } )(),
                    'Current': 'Current',
                    'Notify': 'Notify',
                    'Expired': 'Expired',
                  },
                },
                { 
                  title: 'Work Order Status', 
                  field: 'workorder_state',
                  lookup: {
                    'certified': '',
                    'dispatched': 'Dispatched',
                    'scheduled': 'Scheduled',
                    'pending_approval': 'Pending Approval',
                    // 'certified': 'Certified',
                    'delay': 'Delay',

                    'needs_assignment': 'Needs Assignment',
                    'proposal_requested': 'Proposal Requested',
                    // 'pending_approval': 'Pending Approval',
                    'proposal_approved': 'Proposal Approved',
                    'pending_assessment': 'Pending Assessment',
                    'repairs_rendered': 'Repairs Rendered',
                  }
                },
                {
                  title: 'Days Until',
                  render: (rowData) => daysUntil(rowData.expiration_date),
                  filtering: false,
                },
                {
                  title: 'Expiration',
                  field: 'expiration_date',
                  render: (rowData) => formatDate(rowData.expiration_date),
                  filtering: false
                }
              ]}
              actions={props.actions || [
                {
                  tooltip: 'Dispatch',
                  onClick: (event, data) => quickActionHandler('dispatch', data),
                  isFreeAction: false,
                  icon: () => {
                    return (
                      <i className="fa fa-bullhorn" style={{ color: blue[700] }} aria-hidden="true"></i>
                    )
                  },
                  iconProps: {
                  },
                },
                {
                  tooltip: 'Dispatch',
                  isFreeAction: true,
                  onClick: (event, data) => {alert("Please select Tracking Items to operate on.")},
                  icon: () => {
                    return (
                      <i className="fa fa-bullhorn" style={{ color: blue[700] }} aria-hidden="true"></i>
                    )
                  },
                  iconProps: {
                  },
                },
                /////
                {
                  tooltip: 'Request Estimate',
                  isFreeAction: true,
                  onClick: (event, data) => {alert("")},
                  icon: () => {
                    return (
                        // <Icon style={{ color: grey[50] }}>mail_outline</Icon>
                        <Icon style={{ color: blue[700] }}>monetization_on_outlined</Icon>
                    )
                  },
                  iconProps: {
                  },
                },
                {
                  tooltip: 'Request Estimate',
                  isFreeAction: false,
                  onClick: (event, data) => {alert("")},
                  icon: () => {
                    return (
                        // <Icon style={{ color: grey[50] }}>mail_outline</Icon>
                        <Icon style={{ color: blue[700] }}>monetization_on_outlined</Icon>
                    )
                  },
                  iconProps: {
                  },
                },
                //
                {
                  tooltip: 'Request Invoice',
                  onClick: (event, data) => {alert("Moveing " + data.length + " Tracking Items to their next state.")},
                  isFreeAction: false,
                  icon: () => {
                    return (
                        // <Icon style={{ color: grey[50] }}>mail_outline</Icon>
                        <Icon style={{ color: blue[700] }}>receipt_outlined</Icon>
                    )
                  },
                  iconProps: {
                  },
                },
                {
                  tooltip: 'Request Invoice',
                  isFreeAction: true,
                  onClick: (event, data) => {alert("Please select Tracking Items to operate on.")},
                  icon: () => {
                    return (
                        // <Icon style={{ color: grey[50] }}>mail_outline</Icon>
                        <Icon style={{ color: blue[700] }}>receipt_outlined</Icon>
                    )
                  },
                  iconProps: {
                  },
                },
                ///
                //
                {
                  tooltip: 'Request Certification',
                  onClick: (event, data) => {alert("")},
                  isFreeAction: false,
                  icon: () => {
                    return (
                        <i className="fa fa-certificate" style={{ color: blue[700] }} aria-hidden="true"></i>
                    )
                  },
                  iconProps: {
                  },
                },
                {
                  tooltip: 'Request Certification',
                  isFreeAction: true,
                  onClick: (event, data) => {alert("")},
                  icon: () => {
                    return (
                        <i className="fa fa-certificate" style={{ color: blue[700] }} aria-hidden="true"></i>
                    )
                  },
                  iconProps: {
                  },
                },
                ///
                {
                  tooltip: 'Request Update',
                  onClick: (event, data) => {alert("sending " + data.length + " emails.")},
                  isFreeAction: false,
                  icon: () => {
                    return (
                        // <Icon style={{ color: grey[50] }}>mail_outline</Icon>
                        <Icon style={{ color: blue[700] }}>mail_outline</Icon>
                    )
                  },
                  iconProps: {
                  },
                },
                {
                  tooltip: 'Request Update',
                  isFreeAction: true,
                  onClick: (event, data) => {alert("Please select Tracking Items to operate on.")},
                  icon: () => {
                    return (
                        // <Icon style={{ color: grey[50] }}>mail_outline</Icon>
                        <Icon style={{ color: blue[700] }}>mail_outline</Icon>
                    )
                  },
                  iconProps: {
                  },
                },
                ///////
              ]}
              data={props.columnData}
              title={title}
              options={{
                search: false,
                filtering: props.canFilter,
                pageSize: 10,
                emptyRowsWhenPaging: false,
                selection: true,
                showTextRowsSelected: false,
              }}
              components={{

                Toolbar: props => (
                  <div>
                    <div style={{padding: '0px 10px', 'text-align': 'right'}}>
                      <h5>Batch Actions</h5>
                    </div>
                    <MTableToolbar {...props} />
                  </div>
                ),

              }}

            />
          </div>
        </div>
      </div>
    </Container>
  );
};

export default issueList;`
