### ISSUE TITLE
hi, after hide columns still show up in columnsButton 

### ISSUE THREAD

**Issue by jensysantana** [mbrn/material-table#1878]
hi, after hide columns still show up in columnsButton.

i hide some columns in my table using hidden:true also the show up disabled but still there, have some way to hide columns from there?
![Screenshot (69)](https://user-images.githubusercontent.com/36571423/80836898-b6cd1a80-8bc3-11ea-853b-1d2bc5bbe35e.png)

and also i have space between index and name columns after hide column

**Comment by jensysantana** [comment]
and also i have space between index and name columns after hide column

**Comment by martin-trajanovski** [comment]
Is there a way to show/hide columns but they are still visible in the columnsButton? Because this is breaking change for me and I am not going to update to the last version if this is not possible. This was good functionality because if you want to show/hide a column you should be able to see it somewhere. If you want it totally invisible than you just do not add it in the columns array. Isn't that the right way?

**Comment by jensysantana** [comment]
Ok thank you but I need the Id column totally hide. I Think user no have to see it.
