### ISSUE TITLE
Virtualized huge data with all features

### ISSUE THREAD

**Issue by KhadeerUI** [mbrn/material-table#1897]
I need virtualized huge data(minimum 100K rows and 100 columns). Could I expect the feature in the material-table?

**Comment by oze4** [comment]
[This](https://github.com/mbrn/material-table/issues/891#issuecomment-538129763) may help.

**Comment by oze4** [comment]
Issue has become stale, please reopen if needed.

**Comment by mackankowski** [comment]
Hi all,

I'd like to share my virtualization concept for **material-table** using [react-virtualized](https://github.com/bvaughn/react-virtualized) ([react-window](https://github.com/bvaughn/react-window) and [react-virtual](https://github.com/tannerlinsley/react-virtual) works the same way for me)

https://codesandbox.io/s/material-table-react-virtualized-28umv

Be aware that my solution isn't perfect yet but I hope maybe we could extend **material-table** by this feature someday.

Following issues appear:
- styling: the traditional way of width setting and text aligning don't work as expected
- `validateDOMNesting(...) ` warning because of incorrect element nesting (actually

Feel free to share your experience with combination **material-table** and virtualization solution for expanding such a nice library as it is!

Best regards,
Maciej

**Comment by mackankowski** [comment]
Hi all,

Let's my previous post about virtualization where I share some sample code: https://github.com/mbrn/material-table/issues/891#issuecomment-681986647
