### ISSUE TITLE
Detail Panel Expand Icon

### ISSUE THREAD

**Issue by cmontois** [mbrn/material-table#1961]
**Describe the solution you'd like**
I just want to open a detailPanel in one specific column of the table, and so I want to be able to hide the "expand detail panel icon".

![image](https://user-images.githubusercontent.com/12199643/83117951-01ac5600-a0ce-11ea-84e4-a5e8d0487ce3.png)

**Describe alternatives you've considered**
I have managed to trigger the detailPanelToggle function from the Chip (the green Chip with value 39). But i can't figure out how to hide the icon ^^

Thanks !

**Comment by oze4** [comment]
So you want to hide the green icon?

**Comment by Domino987** [comment]
Or do you want to hide the arrow to the left? If that is true, you can override the icons via a prop and just pass null as the appropriate toggle icon.
See the readme for details.

**Comment by cmontois** [comment]
@Domino987 thanks I didn't notice we could pass null my bad sorry for the issue ^^

**Comment by cristiangabor** [comment]
@cmontois Hi...i have problems  triggering the detailPanelToggle function from onClick() action...Could you tell me how you succeeded ?

**Comment by Gr8tDaNe** [comment]
I've created a custom package that hides the detailPanel column because I couldn't wait for it to be implemented, if you wanna test it, here's the link: https://github.com/Gr8tDaNe/material-table
Once installed you can just use options.renderDetailPanelColumn: false to hide it (remember to implement a rowclick or another way to open it). 

I'm a noob so this is probably not the ideal way of publishing a package, but I was short on time. 
I'll submit a pull request later today.
