### ISSUE TITLE
Resolve custom columns with Remote Data fetch

### ISSUE THREAD

**Issue by harveysanders** [mbrn/material-table#1989]
**Is your feature request related to a problem? Please describe.**
I'd liked to change column headers based on the results from remote data.

**Describe the solution you'd like**
I'd like to be able to pass resolve `columns` along with `data` in the Promise passed to data
https://material-table.com/#/docs/features/remote-data
```jsx
<MaterialTable>
  data={(query) => {
    return fetch('url')
      .then((data) => {
        const columns = createCustomColumns(data); 
        return {
          data,
          // Would be nice to be able to pass
          // columns here and update the table state
          columns,
          pageSize: query.pageSize,
          pageIndex: query.page
        };
      })
   }}
</MaterialTable>

```

**Describe alternatives you've considered**
I could use React's state outside of the Material Table and pass in columns via props, but at that point, I should just pass and `data` as well and not use this remote data feature. 

Thank you. This library is awesome!

**Comment by oze4** [comment]
Hey @harveysanders thank you for your question! Would you mind using the [links found here](https://github.com/mbrn/material-table/blob/master/.github/ISSUE_TEMPLATE/help.md) to create a minimal reproducible example of the issue you are having?

With that being said, you should be able to put whatever data you are using for `columns` in your state, so that you can dynamically set it to whatever you want.
