### ISSUE TITLE
onRowUpdate input value emitting as [object Object] 

### ISSUE THREAD

**Issue by rkpip3** [mbrn/material-table#2071]
**Describe the bug**
onclick of onRowUpdate button input value emitting as [object Object] and if there is two input, act as two way data binding please see the StackBlitz: 

[StackBlitz](https://stackblitz.com/edit/usb66k)

**To Reproduce**
1. Click on 'update/edit icon'
2. there 3rd  & 4th input (" [object Object] ") 
4. its seems there is two way data binding

**Expected behavior**
On click all input should be able to show placeholder data & there should not be two way data binding

![screenshot-stackblitz com-2020 06 19-00_17_12](https://user-images.githubusercontent.com/65766575/85060115-4f464b00-b1c2-11ea-82dd-5ce4b565c843.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : chrome
 - Version : 83.0.4103.106 

sorry for my bad english.

**Comment by VLRTroll** [comment]
Once you define the field of the column as 'birthCity', the value that will be attributed to the column is data[currentIndex].birthCity, which is an object. Because of that you wrote `render: (rowData) => rowData.birthCity[0].region,`  to display the correct data. So you'd do the same to the editComponent. I'll show you 2 ways to fix this:

1. Change the field property to `field: "birthCity[0].region",`

2. Set a editComponent: 
```
editComponent: (props) => (
          <Input 
            {...props} 
            value={props.rowData.birthCity[0].region}
            onChange={(e) => {
              const currentObject = props.rowData.birthCity[0];
              currentObject.region = e.target.value;
              
              // This works like setState
              props.onChange([currentObject,props.rowData.birthCity.slice(1)])
            }}
          />
        )
```

**Comment by rkpip3** [comment]
@VLRTroll  Thank you very much Its works...
