### ISSUE TITLE
Numeric data truncation and alignment in csv export of material table

### ISSUE THREAD

**Issue by suresh0308** [mbrn/material-table#2095]
Hi,

I need help in alignment of numeric data in text fields of 'Export as csv' file. Also the data is getting truncated if the value is numeric and starts with zero (e.g. 0907 is coming as 907 in csv).

Attached snap of my csv file in which it shows, in the text field if value is complete numeric it is getting right aligned instead of left and if value is complete numeric and starts with 0, then value is getting truncated (refer last record in the snap, actual value is 0123 but it got downloaded as 123)

Need help in fixing these two problems in export as csv function.

I referred the url and coded the function to export the data.
https://github.com/mbrn/material-table/blob/b237bb3f5172d9a690671e4c4d8d3818b7256a8e/src/m-table-toolbar.js#L19-L37 

![git_ticket](https://user-images.githubusercontent.com/67435460/85774480-82e22180-b73c-11ea-8200-2166b215a673.JPG)

**Comment by suresh0308** [comment]
Can anyone help me with this problem?

**Comment by Nabellaleen** [comment]
Open the `csv` file with a text editor instead of "table editor" : you will see that the notion of "alignment" has no sense in the context of a csv

It's your table editor software which choose to align the data depending of its guessed type. And there is no option in csv format to change that.

If you want to have more control on the final "render" in a given "table editor", you can export a file specific to this editor (xlsx for example for Microsoft Excel), but it's a lot more complicated and "vendor-locked" than a CSV

You can also "cheat", by adding a `'` before the element ; for example `'1136` instead of just `1136`. Table editor will now consider the data as a string (because there is a string character) but will not display the quote. BUT, by doing that, you "modify" your data, so it can be a problem, especially for ids : `1136` is different from `'1136`, so you can have mismatch behaviors due to that

The best is : do nothing, the alignment is not a problem :) (And you can configure your table editor to change the type and the alignment of a column, if it's bothering you)
