### ISSUE TITLE
detailPanel hide icon column 

### ISSUE THREAD

**Issue by cristiangabor** [mbrn/material-table#2098]
Is there a way to hide the whole column where the icons that expand detailPanel resides ? 

I have disabled/null icon but there is still column space left 
![image](https://user-images.githubusercontent.com/12631346/85803650-546e4180-b750-11ea-92fb-5f7e4e9d568f.png)

**Comment by Gr8tDaNe** [comment]
This would be great, yes. Some way to access that column and apply normal column options to it maybe. I've been going through the source but am quite new to React so not sure where to begin.

**Comment by Gr8tDaNe** [comment]
I did it. I've created a custom package that hides the detailPanel column because I couldn't wait for it to be implemented, if you wanna test it, here's the link: https://github.com/Gr8tDaNe/material-table
Once installed you can just use options.renderDetailPanelColumn: false to hide it (remember to implement a rowclick or another way to open it).

I'm a noob so this is probably not the ideal way of publishing a package, but I was short on time.
I'll submit a pull request later today.

Set detailPanelColumnAlignment: "right", as well or the table won't render properly. I'll look into why that is when I have time.
