### ISSUE TITLE
Type of RowData

### ISSUE THREAD

**Issue by theqp** [mbrn/material-table#2141]
Hello!
What type `RowData` can be?
The documentation states this:
```javascript
const data = [
    {name: 'Mehmet', surname: 'Baran', birthYear: 1987, birthCity: 63},
    {name: 'Zerya Betül', surname: 'Baran', birthYear: 2017, birthCity: 34},
]
```
This seems to be a `Record<string, string | number>` for me. `RowData extends object` is too broad if the documentation is exact.
Some examples which can be `object`:
- `new Object()`
- `new Date()`
- `new Array()`
-  `{ 1: new Object() }`
-  `(n: number) => n + 1`

**Comment by ya332** [comment]
columns have type argument, and type argument can take ```'boolean', 'currency', 'date', 'datetime', 'numeric', 'string', 'time'``` values.

**Comment by Domino987** [comment]
There is also the possibilty to access deeper levels of the objects with a column field e.g. field: "user.id.created". A record would not allow that. But yes the outer most object must be a record with value unknown maybe. The problem is that with the render prop, any object or even plain numbers could be used as rowData.
