### ISSUE TITLE
tableData methods/values

### ISSUE THREAD

**Issue by j0nathanchuang** [mbrn/material-table#2180]
In many examples on [the Material Table docs](https://material-table.com/#/docs/features/), the table data is being modified using, for example, `rowData.tableData.checked` or `rowData.tableData.id`. 

### I was wondering if there is a comprehensive list of all the values/methods you can use from `tableData`. 
I have yet to find a resource like this in the documentation or on StackExchange.

For more clarification of what I'm referring to when I say `tableData`, here's how I'm using it for my delete selected rows action:
```
actions={[
          {
            tooltip: 'Remove Selected',
            icon: () => <DeleteOutline />,
            onClick: (event, rowData) => {
              if (window.confirm("Are you sure you want to delete " + rowData.length + " item(s)?")) {
                let temp = [...data]
                for (let i = rowData.length - 1; i >= 0; --i) {
                  let index = rowData[i].tableData.id;        //interested in this!
                  temp.splice(index, 1);
                }
                setData(temp);
                console.log(rowData.length + ' rows deleted.');
              }
            }
          },
```

**Comment by VLRTroll** [comment]
Unfortunately, I think don't have a list of all attributes which can appear in tableData. But taking a look in the material-table source code, it's possible to list some (or all) of them:

**In row related components: (Body Row, Edit Row, ...)**

1. `id: number` - The index of the row
1. `checked: bool` - If the row is selected
1. `editing: string` - Which is the current edit mode ('update', 'add','delete')

**In column related components:**

1. `id: number` - The index of the column
1. `filterValue: Array` - Filter info
1. `groupOrder: number` - Column index in the current group
1. `columnOrder: number` - Column index if the columns were reordered

@j0nathanchuang, I'm not totally sure about each attribute role, because the most of time I just use the "id" property. But I hope you can enjoy it.

**Comment by j0nathanchuang** [comment]
Thank you @VLRTroll
