### ISSUE TITLE
Parametric lookup

### ISSUE THREAD

**Issue by victorsmits** [mbrn/material-table#2245]
Is it possible to get a parametric lookup, so the dropdown will be different in each row?

**Comment by nweajoseph** [comment]
i think this would actually be really useful. here's an example:

```
name     | room         | table
Bob      | Dining Room  | Grown Ups Table
Sally    | Dining Room  | Kids Table
Jill     | Game Room    | Pool Table
```

if you want to let users change the seating assignments in this table, how does it work? the possible list of `table`'s is relative to the `room` the user has selected in each row. "Pool Table" is not a valid choice for a person that's sitting in the "Dining Room"

this kind of thing is impossible on the current implementation of `lookup`. it's also impossible to implement manually in user land, because you would need to have state shared between the `editComponent` props of two different columns. that's impossible because `React.useState()` can't be called from the `render()` method of columns.

one way it could work is if `lookup` were implemented as a function that receives the table data.

```js
columns = [
  { field: "name" },
  { field: "room" },
  {
    field: "table",
    lookup: (tableData) => getTablesForRoom(tableData.data[index].room)
  }
]
```
