### ISSUE TITLE
Expanded Multi-level Grouping Collapses When You Select A Row

### ISSUE THREAD

**Issue by umeshajb** [mbrn/material-table#2258]
**Describe the bug**
I have a table that allows for grouping with multiple columns. I also allow for row selection. The issue I am having is if you group more than one column and select a row within that group the expanded group with the table rows collapses. This is cumbersome for the user if they want to select multiple rows within a group, each time you select a row it will collapse the expanded group and the user will have open the group again to select another row. This seems to be an issue only when you group by multiple columns, it works correctly when you just have one column.

**To Reproduce**

1. Group by multiple columns
2. Expand all the grouping columns
3. Select a row within a group
4. The group expansion collapses and if you need to select another row from the group you will have to expand the group 

**Expected behavior**
When the grouping columns are expanded it should not collapse automatically when you select a row. I would expect it to stay open.

**Desktop (please complete the following information):**

- OS: Mac OS Catalina
- Browser: chrome
- Version 84.0.4147.89

**Comment by FalkF** [comment]
I can confirm this bug, I also might be able to take a closer look at this later.

**Comment by FalkF** [comment]
I took a little dive into `data-manager.js` and could nail the problem down to `findGroupByGroupPath()` returning the wrong group since the `groupsIndex` gets out of sync with  `this.groupedData` in the second dimension of the array. This happens while adding the second grouping somewhere in `sortData()` 

I suspect https://github.com/mbrn/material-table/blob/5e9ef9affbc83db80301c4edee4306aabcc3701f/src/utils/data-manager.js#L958 to be the source of the problem since this is a shallow copy and it would explain why the first grouping is not affected. I could not fix it yet tho, maybe someone with deeper understanding could help here ;)
