### ISSUE TITLE
Is there a way we could save all the applied filters, grouping, order by etc.. operations performed on the table and save it and re-apply them to load the table in the same state?

### ISSUE THREAD

**Issue by sampathkatari** [mbrn/material-table#2271]

**Comment by brodao** [comment]
Gentlemen,

I implemented something similar, without modifying the component itself due to urgency. The solution can be seen at https://github.com/totvs/tds-vscode/tree/dev/src/monitor, but this is specific to VSCode.
In the next few days, I intend to implement it in the component due to not being able to obtain some properties, e.g. added columns for grouping.

I'm available.
Sorry my bad english.

**Comment by sampathkatari** [comment]
@brodao Thank you for the response. Meanwhile i tried to do a work around using tableRef. Will look at your code as well.

**Comment by bishonen** [comment]
> @brodao Thank you for the response. Meanwhile i tried to do a work around using tableRef. Will look at your code as well.

How does tableRef become useful for what you're after (honest question)? I'm looking to implement something similar.

**Comment by sampathkatari** [comment]
Using ref we could access every state variable and the method that is part of the component right. So in that way am accessing the data that i need at a particular state when needed and saving them.
