### ISSUE TITLE
https://material-table.com/#/docs/features/remote-data - refresh data issue

### ISSUE THREAD

**Issue by C2FO-Ruchin** [mbrn/material-table#2297]
Getting below compile error on refresh data API. 

![image](https://user-images.githubusercontent.com/56113982/89733938-917b6280-da76-11ea-9c1a-0698a18b57ae.png)

also, wanted to check if some can help how we can refresh data dynamically based on data change in graphql { loading, error, data } = useQuery(QUERY);

**Comment by Domino987** [comment]
Thats a typescirpt and not material-table problem. You need to tell ts what the ref is suppose to be or otherwise its unknown. So change it to `React.createRef<any>()` so that ts can infer the type. Since the tableRef is complex and changes frequently, you should just use any and use that without the type safty.
What would the change trigger?

**Comment by C2FO-Ruchin** [comment]
Got it thanks.
What would the change trigger? - It supposes to refresh the data after an edit or add new data to data table.
