### ISSUE TITLE
Validation doesn't work on row add.

### ISSUE THREAD

**Issue by Mizan-Rifat** [mbrn/material-table#2353]
validation doesn't work when adding a row.but it works perfectly on row update.any way to use validation on row add??

**Comment by shubham-sisodia** [comment]
Any update on this?

**Comment by Hojondo** [comment]
Update this bug, to anyone who maybe fall into the same situation.

First of all I wrote code like:
`validate: rowData => rowData.name !== '' ? true : 'Name can not be empty'`
I can click submit(check icon) btn immediately once I see the new editable row, but if I edit one word and delete it to empty field, the check icon change to disabled status as expected.
then I thought it might because that the inital value is null or undefined but ''
so I change the code to:
`validate: rowData => (rowData.name ? true : 'Name can not be empty')`

And it works
