### ISSUE TITLE
Collapsible table feature like material UI

### ISSUE THREAD

**Issue by m4c-4rthur** [mbrn/material-table#2422]
I would like to know if material table is supporting something like collapsible table feature in material UI

https://material-ui.com/components/tables/#collapsible-table

I checked the the Tree Data feature, but it It will not fulfill my requirements since it's assuming that both tables have the same columns structure, I want to embed entirely different table.

**Comment by kkirsche** [comment]
Not that I have seen, but would love to know this as well

**Comment by cf-232** [comment]
Hi, @m4c-4rthur , here a demo I used before for asking some other questions. 
          https://codesandbox.io/s/material-table-sub-table-edit-function-iybwu?file=/src/table.js

I added nested table myself. I am not sure if this is a proper way to do it since there is no such use case on official document/website. Or it might lead to poor performance. 

But hopefully this can give you some reference on how to do the nested table.
