### ISSUE TITLE
When material-table is loading, the table overlaps the components over it

### ISSUE THREAD

**Issue by VictorPotes** [mbrn/material-table#2448]
**Describe the bug**
I have a custom button on the material-table, when it's pressed the table start to be loading while a modal appears over it. The problem is that table while is loading is overlapping the modal.

**To Reproduce**

1. Add a button to the table with the following actions: icon, tooltip, onClick, isFreeAction = true}
2. In onClick function I call a Modal to appear on the screen.
3. Create useEfect that changes the isLoading flag of the table to true when Modal is open and false when Modal is closed.
4. While the Modal is on the screen, you will realize that the table is loading over the modal.

**Expected behavior**
What I hope to happen is that the table keeps loading while the Modal is on the screen without being overlapped by the table.

**Screenshots**
This is the table with the button to open the Modal

![image](https://user-images.githubusercontent.com/25420216/92945021-53c57d00-f41a-11ea-8dba-85fe0f953345.png)

Once the button, the modal is open and the table while is loading overlaps the Modal

![image](https://user-images.githubusercontent.com/25420216/92945460-e9610c80-f41a-11ea-90ab-2d9e4f8aee1c.png)

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Google Chrome

Thank you so much for your support!

**Comment by corneliushka** [comment]
You should take a look on the zIndex of your components (either the Modal and the Material Table layout), and adjust somewhere. I recommend to not override the material-table but instead your modal.

Otherwise, if you use mui components, be in the know that every component has a default value. You can override these by applying a custom value on the top. https://material-ui.com/customization/z-index/ 

A personal example : I had once a popover (Popper from @material-ui/core) which had an overlap with the table, then i gave it a z index of 1210 and the problem was solved (indeed, I think that the table has a z index between 1000 and 1200).

**Comment by VictorPotes** [comment]
@corneliushka You are right, it worked for me. Thank  you!
