### ISSUE TITLE
Selection is broken when onSelectionChange updates a state variable

### ISSUE THREAD

**Issue by cdruck** [mbrn/material-table#2502]
Simplistic example: https://codesandbox.io/s/material-table-selection-broken-on-update-state-70db8

Any click on checkboxes sets the state variable to the latest selected row, and the selection on the table is cleared out.

Desired behavior: selection works normally, and the state variable is updated so it can be used elsewhere...

**Comment by PauloJFCabral** [comment]
I am with the same problem. 

Any fix for this?

**Comment by dlemburg1** [comment]
I have this same issue when changing the state of a dropdown in the Toolbar.

**Comment by vijaycharan16** [comment]
Hi dlemburg1,
Could you help by giving an example? how did you use useMemo

**Comment by dlemburg1** [comment]
Hey @vijaycharan16,

The background behind this example: I am using apollo/graphql to fetch some 'foos'. Material-Table didn't like that the data structure returned by apollo is immutable (because it stores a 'tableData' property to track each table row's data). So to release the foos' reference, I just mapped over it inside of useMemo. This allows the newly created 'entities' array to be mutable - which satisfies Material-Table - but also to keep the same reference - via 'useMemo' - throughout the component's lifecycle changes (i.e. responding to a state change).

```javascript
const [
    lazyFetchEntities,
    { data: { foos = [] } = {}, loading }
  ] = useLazyQuery(FETCH_ENTITIES, { fetchPolicy: 'network-only' });
  const entities = useMemo(() => foos.map(x => ({ ...x })), [foos]);
  
  return <Table data={entities} />
```

**Comment by vijaycharan16** [comment]
@dlemburg1,
Thank you very much for the response, I will give a try.
