### ISSUE TITLE
Custom cell rendering: add value param for shared rendering method

### ISSUE THREAD

**Issue by peacechen** [mbrn/material-table#2679]
- #### Please include a demo of the issue/behavior/question you have

I would like to use a shared render method for all the cells. Unfortunately the render callback only provides the entire rowData object, not the particular cell that it's rendering. This makes it impossible to pass a single render method to all of the columns.

Here's an example that sets all of the columns' render callbacks after the columns have been created:
```
  for (let col of columns) {
    col.render = (rowData, secondParam) => {
      return (
        <div style={{minWidth: 20, maxWidth: 200}}>{secondParam is the value "row"}</div>
      );
    };
```

**Is your feature request related to a problem? Please describe.**
See above.

**Describe the solution you'd like**
Add an additional parameter to the render callback with the cell's value. This should be trivial since material-table has the cell's data that it's rendering.

**Describe alternatives you've considered**
Each column's entry would need to assign a render method individually, bloating the code. Example:
```
  const columns = [
    {
      title: "col1",
      field: "col1Field",
      render: myRenderMethod("col1Field"),
    },
    {
      title: "col2",
      field: "col2Field",
      render: myRenderMethod("col2Field"),
    },
    {
      title: "col3",
      field: "col3Field",
      render: myRenderMethod("col3Field"),
    },

    ...

  ];
```

**Comment by vatavian** [comment]
I figured out how to do this kind of thing by using a reference to the column when creating my renderers. (my working code below) I have heard that this only works when you "let col" because then the reference will still be good later during rendering. This is more flexible than the suggestion of passing the row value for the current column because you can refer to other properties of the column when deciding how to render. It is more complicated though, since you can't include the reference to the column this way when you are first creating it but rather have to assign the renderers in a second step after defining the columns. 

In the best of both worlds, this feature request would go forward, but with a second argument that is the column object currently being rendered. This would allow more flexible reuse of render methods as I show below, but more easily because they could be assigned as the column is first created.

In my example below, I am accessing this.props.data and this.props.columns as they arrive in my class (they were sent as JSON that was generated on the server) and I adjust them here before creating the material-table. 

`
import { format } from 'date-fns' // yarn add date-fns@2.0.0-alpha.21 (newer versions break pickers)
import DateFnsUtils from '@date-io/date-fns'; // yarn add @date-io/date-fns@1.x
import { MuiPickersUtilsProvider, KeyboardDatePicker } from "@material-ui/pickers";
//...
    var data = this.props.data;
    for(let col of this.props.columns) {
      if (col.is_link) {   // is_link is a custom tag I added so I know to make these into links here.
        // When I set col.is_link, I set values on each row for both that column's field and field_path.
        if (col.lookup) // when using a lookup, use that text.
          col.render = rowData => <a href={rowData[col.field + '_path']}>{col.lookup[rowData[col.field]]}</a>
        else
          col.render = rowData => <a href={rowData[col.field + '_path']}>{rowData[col.field]}</a>
      }
      if (col.dateSetting) { // render using the column's custom format, not locale, and use customized picker
        col.render = rowData => format(rowData[col.field], col.dateSetting.format)
        col.editComponent = ({ value, onChange }) => (
          <MuiPickersUtilsProvider utils={DateFnsUtils}>
            <KeyboardDatePicker
                autoOk="true"
                variant="inline"
                format={col.dateSetting.format}
                value={value}
                onChange={onChange}
            />
          </MuiPickersUtilsProvider>
        )
        // data comes in as strings like "2021-01-22". This map turns them into Date objects.
        // 'T00:00' makes them local time not UTC, otherwise they sometimes display as a day off.
        data = data.map(row => { row[col.field] = new Date(row[col.field] + 'T00:00'); return row;});
      }
      // Maybe this should be the default behavior for currency? Anyway it is easy to fix here:
      if (col.type == 'currency')
        col.customSort = (a, b) => a[col.field] - b[col.field];
    }
`

**Comment by peacechen** [comment]
Thanks @vatavian for sharing your work-around. I encourage you to migrate to [@material-table/core ](https://github.com/material-table-core/core) which is actively maintained. I plan to submit a PR there for this feature.
