### ISSUE TITLE
Unable install material-table with @data-io@1.69.2 and @material-ui/core@4.11.2

### ISSUE THREAD

**Issue by jagadeeshkoka** [mbrn/material-table#2711]
# Guidelines

Unable to install material-table
- #### Please try to be as detailed as possible
To reproduce 
`npm i material-table`
`npm i material-table@1.69.2
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: myahb-ui@0.1.0
npm ERR! Found: @date-io/core@2.10.6
npm ERR! node_modules/@date-io/core
npm ERR!   @date-io/core@"^2.10.6" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @date-io/core@"1.3.6" from material-table@1.69.2
npm ERR! node_modules/material-table
npm ERR!   material-table@"1.69.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
`
@date-io and @material-ui/core is already installed successfully

**Comment by oze4** [comment]
Hey @jagadeeshkoka! Thanks for bringing this to our attention.

Unfortunately, mbrn appears to have become rather busy as of late. Since he is the only person that has permissions to commit, and with the hopes of keeping this project alive/updated, myself and a couple other contributors (anyone is welcome to join us!) have created a fork of this repo, [`@material-table/core`](https://www.npmjs.com/package/@material-table/core), which we are actively applying updates to.

We are keeping it as a fork so we can merge when mbrn comes back. 

[You can check out the repo here](https://github.com/material-table-core/core), and you can find [instructions here](https://github.com/material-table-core/core#usage) on how to use this fork.

It looks like this error was [recently introduced](https://github.com/material-table-core/core/issues/13) (`@material-table/core` inherited this issue from `mbrn/material-table`), but we have resolved it in `@material-table/core`. 

Please let me know if you have any questions.

**Comment by jagadeeshkoka** [comment]
Hey @oze4 , thanks for the info, I got it worked by adding this flag `--legacy-peer-deps` not sure how accurate is this workaround. 

Thanks,

**Comment by oze4** [comment]
Glad you got it resolved!
