### ISSUE TITLE
Invariant failed: Draggable[id: 2]: Unable to find drag handle on SSR, with Next JS

### ISSUE THREAD

**Issue by aliburhankeskin** [mbrn/material-table#2765]
### On every click and every page refresh , output  console 

![error](https://user-images.githubusercontent.com/32386753/106482034-1abba100-64be-11eb-995a-84d432e7c390.PNG)

### _document.js

`
    import { ServerStyleSheets } from '@material-ui/core/styles';
    import { resetServerContext } from 'react-beautiful-dnd';
`

`   

      MyDocument.getInitialProps = async (ctx) => {
          const sheets = new ServerStyleSheets();
          const originalRenderPage = ctx.renderPage;
          ctx.renderPage = () => originalRenderPage({
            enhanceApp: (App) => (props) => {
              resetServerContext();
              return sheets.collect(<App {...props} />);
            },
          });

`

Can you please fix this error.

@mbrn

**Comment by mtahagocer** [comment]
This is a problem with react-dnd. How to work stable with this ??

**Comment by ashu2305** [comment]
@aliburhankeskin  would drag and drop feature work  or not ?

**Comment by aliburhankeskin** [comment]
Yes, drag and drop feature is working. Additionally this logs not showing on production and everythign works fine.

**Comment by cbaker** [comment]
Having this issue in tests using jsdom. Any solutions?

**Comment by Emyboy** [comment]
Same issue here as well

**Comment by Emyboy** [comment]
Check if this is any good => https://codedaily.io/tutorials/185/Using-react-beautiful-dnd-with-NextJS  @aliburhankeskin

**Comment by aliburhankeskin** [comment]
Thank you for answering. Sorry it didn't work @Emyboy

**Comment by Jak-Ch-ll** [comment]
The article posted by @Emyboy refers to an older version of Next, but it describes the correct root of the issue: **Nextjs** tries to pre-render the page on the server, while **react-beautiful-dnd** needs the browser (possible the window object) to be working correctly.

Two ways to get rid of the error messages:
1. If you don't need the draggable-feature, just remove it in  Material-Tables options
```js
<MaterialTable
    columns={columns}
    data={data}
    options={{ draggable: false }}
/>
```

2. If you want to use the draggable-feature, you can [dynamically import](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr) the MaterialTable component and deactivate server-side-rendering for it:
```js
// important: remove the normal import statement
const MaterialTable = dynamic(() => import("material-table"), { ssr: false });
```

From my point of view this is not a bug, since material-table(or react-beautiful-dnd for that matter) is not designed for SSR.

**Comment by aliburhankeskin** [comment]
Thanks for your answer @Jak-Ch-ll .  I'll use option 2.

**Comment by awaism551** [comment]
https://github.com/atlassian/react-beautiful-dnd/issues/1756#issuecomment-735369084
this comment will help while resolving issue in nextjs
