### ISSUE TITLE
Focus lost on filter input after remote data load

### ISSUE THREAD

**Issue by tejasatara** [mbrn/material-table#2778]
Whenever a user tries to search on a column filter, focus is lost after every character typed in remote data load mode.
It is not practically possible for a user to filter a long string when focus is lost after every character typed.

1 - Type character on a column filter
2 - Observe that the focus is lost on column filter

Expected behavior: Filter selections should persist focus post remote data render
I don't see a configuration or any prop/method exposed on the library that I can use to tweak this behaviour.

**Comment by mackankowski** [comment]
I've figure out a little **WORKAROUND** for losing focus (after re-rendering and losing the original instance of elements):


```
  const [focusedElementName, setFocusedElementName] = useState('');

  useEffect(() => {
      if (focusedElementName && tableData) {
          const focusedElement = document.querySelector(
            `input[name="${elementName}"]`,
          );
          (focusedElement as HTMLElement).focus();
        }
  }, [focusedElementName, tableData]);

  <input onChange={setFocusedElementName('foo')
```
 
This example with using the `onChange` event is fine for custom filter components that we can define in `columns.title`. For native (material-table's) filter components, we should think about attaching onChange on some other place (`onSearchChange`? - I'm not sure now...). Take notice a real solution for your issue is to not losing the instances (re-rendering) the original element where filters are (or an entire table element - I believe it's a library's inner issue).

Good luck!
