### ISSUE TITLE
Add data formatting feature

### ISSUE THREAD

**Issue by mbrn** [mbrn/material-table#28]
Data formatting for datetime, money etc.

**Comment by mbrn** [comment]
rendering boolean or datetime values cause exception or nothing to render. getValue method must return back string or react component for every case

**Comment by json2d** [comment]
Hey this will be a useful feature

Each column prop can include a format function can will be applied to each value when rendered.

Leaving the underlying value intact will be better so that sorting still works as expected (eg. datetimes), but filtering and searching would need to consider the formatted values
