### ISSUE TITLE
Browser becomes non-responsive when minBodyHeight is set dynamically and columns array is a react state. 

### ISSUE THREAD

**Issue by vazra** [mbrn/material-table#2820]
- #### Please include a demo of the issue/behavior/question you have
Demo : 

https://codesandbox.io/s/material-demo-forked-zo542?file=/demo.js 

- #### Please try to be as detailed as possible

Note: this will not happen if you either if minBodyHeight is not set with respect to state, or column is just a var/const (not react state object)

**Describe the bug**
Go to the above link, click on the right-top button (fullscreen icon) continuously multiple times, the browser will get non-responsive. 

**To Reproduce**

1. Go to https://codesandbox.io/s/material-demo-forked-zo542?file=/demo.js 
2. Click on right-top fullscreen button multiple times continuously 
3. the browser will become non-responsive

**Expected behavior**

There shouldn't have any performance issue while changing body-height with state

**Screenshots**

<img width="1816" alt="Screen Shot 2021-03-11 at 12 33 25 AM" src="https://user-images.githubusercontent.com/7609895/110713209-cebcf400-8201-11eb-950f-578e807f25bd.png">

<img width="113" alt="Screen Shot 2021-03-11 at 12 32 50 AM" src="https://user-images.githubusercontent.com/7609895/110713214-d2e91180-8201-11eb-9eb6-e45104734c89.png">

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Brave V1.21.74 & Chromium 89

**Comment by solonik1** [comment]
Same issue here. Who can help? Pls

**Comment by unfinishedteleporter** [comment]
Not a solution to the actual issue, but for anyone else running into this problem, if feasible you could try using material-table-core.
I.e in the provided demo, replacing "material-table" with "@material-table/core" (in both the js and the package.json) appears to resolve the issue (at first glance anyway).

I stumbled onto this open issue from #2836 while trying to figure out why my filter fields were maintaining the same value between unmounts of the component (so far it seems to be related to where the columns object is declared, I think its mutated rather than copied wrt filters, or more likely I'm just doing something silly)

**Comment by vazra** [comment]
i don't think this is fixed
