### ISSUE TITLE
CSV export breaks with ',' comma into new cell

### ISSUE THREAD

**Issue by arpitalopa** [mbrn/material-table#289]
CSV export breaks with ',' comma into new cell

**Comment by mbrn** [comment]
Hi @arpitalopa ,

Which version do you use?

If you use latest version of material-table. We already fixed this problem. but you should remove node_modules and package-lock.json(or yarn). Then npm install every dependency again. 

Because we fixed this problem with filefy@1.7.0 and upgrade material-table to it. Your project may use filefy@1.6.0 still. Please check it.

**Comment by arpitalopa** [comment]
Thanks for your reply.
