### ISSUE TITLE
Possible memory leak when updating data frequently?

### ISSUE THREAD

**Issue by RomanBogatikov** [mbrn/material-table#2914]
I get data from API that I put in React Context. The data updates frequently (every second). I need to render multiple tables on the screen with different filters applied to this data. That's why I created a wrapper component for table and put the data from Context to state of this component (copy it with Object.assign() so that every table gets its own instance of data array).
After letting the project run for a few hours I notice a significant increase in browser's memory heap size (I use Chrome) that causes a slowdown. 
Am I doing something wrong?
My issue doesn't seem to be related to #2650. 

The version of the material-table package is 1.69.3.
The repo with demonstration can be found here: https://github.com/RomanBogatikov/material-table-memory-leak

**Comment by leom806** [comment]
Hey guys!

A friend of mine and I were having memory leaks here in our application too.
We have a screen where there is one single table with a select-option field to filter the table, refetching data from our API.

Running some heap snapshots, one at the initial page load and one after 10 clicks, we get these results:

Initial Page Load:
![image](https://user-images.githubusercontent.com/7718776/122147477-5af93b80-ce2f-11eb-9d22-6b81cccaf1a0.png)

After 10 selections:
![image](https://user-images.githubusercontent.com/7718776/122147495-63517680-ce2f-11eb-9b78-ed5e5808471f.png)

Inspecting a little further we found that the issue is related to the function `setColumns` in the `src/utils/data-manager.js` and that, possible, there are some strings not being garbage collected in there.

Also, setting the `const undefinedWidthColumns = []` made the memory leak to stop occurring, proving us that the issue is in there, not sure exactly what is causing it, though.

As an alternative, `material-table-core` did changed that piece of code and it seems to be working smoother.

Hope that helps!

**Comment by RomanBogatikov** [comment]
Thanks for your reply, @leom806 . I seem to have accidentally used material-table/core in my demonstration of the problem. I checked to see if there are any issues with styling/width/initialWidth that you mentioned and there doesn't seem to be a problem with that (probably because I used material-table/core fork as you have mentioned). However, heap size still increases significantly over time and I can't trace the root of the problem.

**Comment by kapalex** [comment]
Can confirm there is a memory leak, which means that in cases where the table is being redrawn frequently it can cause the app to crash.

Switched to material-table/core as well until it might be solved.

**Comment by aclave1** [comment]
I'm seeing the same issue in my application with relatively innocuous code. We poll every 30 seconds for some data(just a few rows) and pass it to the data prop. After a few minutes, the application crashes with the memory-allocation exceeded error. I'm also seeing it in setColumns of data-manager.js. Here's a link to the code where we're running this: https://github.com/terragraph/tgnms/blob/6a0385c392d816020cd993d0f233e0a05cd25425/tgnms/fbcnms-projects/tgnms/app/views/tables/NetworkPlanning/PlansTable.js#L36
