### ISSUE TITLE
asterisk for required fields

### ISSUE THREAD

**Issue by shailendra2906** [mbrn/material-table#2979]
Hi,
I have a requirnment where i need to put a red asterisk on selected header columns to show required fields. Is there any existing way to do that?

**Comment by janderson215** [comment]
I use a custom editComponent when defining the columns (style to your needs)

```export const EditInput = (props) => (
	<TextField
		{...props}
		value={props.value || null}
		onChange={(e) => props.onChange(e.target.value)}
		size='small'
		inputProps={{ style: { fontSize: 10, paddingTop: 8 } }}
		divStyle={{ padding: 0, marginTop: -4, marginBottom: -4 }}
	/>
);```

I would either hardcode in the * at the end of the label on the required fields. Or if you want to add other functionality, add a `required` property and use that as a flag to control multiple style details/functionality.

**Comment by shailendra2906** [comment]
Can you please elaborate on how the required property is going to give me a red asterisk on my particular column name.

**Comment by janderson215** [comment]
The asterisk won't actually show up in the column header, unfortunately. I don't know how that can be done. To elaborate a bit more on my previous comment, this is to change the styling of the input field when you are Adding or Editing a row in the table.

Another requirement is that you would need to have input validation (I use Yup) if you have not already implemented it.

```
const StateExcludesSchema = {
		state: Yup.string().label('State').max(2, '2 chars max').required(),
		exclude_type: Yup.string().label('Exclude Type').max(4, '4 char max').required(),
	};

	const columns = [
		{
			title: 'State',
			field: 'state',
			editComponent: (props) => <TableSelect {...props} data={states} />,
			validate: validator(
				Yup.object().shape({
					state: StateExcludesSchema.state,
				})
			),
		},
		{
			title: 'Exclude Type',
			field: 'exclude_type',
			editComponent: (props) => <TableSelect {...props} data={excludeTypes} />,
			validate: validator(
				Yup.object().shape({
					exclude_type: StateExcludesSchema.exclude_type,
				})
			),
		},
	];
```

Here is my `validator` function:
```

export const validator = (schema) => (values) => {
	try {
		schema.validateSync(values, { stripUnknown: true });
		return { isValid: true, helperText: '' };
	} catch (e) {
		return { isValid: false, helperText: e.message };
	}
};
```
This would get you something like this, but you would swap the dropdowns for the `MaterialTableEditInput` I posted previously.
![image](https://user-images.githubusercontent.com/1614038/128579640-5f7f741f-2448-4d9a-bc4e-22e2fd205b8c.png)

Sorry if I took you in the wrong direction and the requirement is that you absolutely must have an asterisk in the column header. I was suggesting an alternative way to indicate the requirement of the field.

Another note on the asterisk: your use case may be better suited for the asterisk, but as far as I know, the current trend is to add `(optional)` as a modifier when a field is NOT required, rather than indicating when it IS required.
