### ISSUE TITLE
how to set tooltip string in action button to have multiple lines

### ISSUE THREAD

**Issue by sstolzenberg** [mbrn/material-table#3005]
Hello,
I am refering to
https://material-table.com/#/docs/features/actions
"Usage":
<MaterialTable
  // other props
  actions={[
    {
      icon: 'save',
      tooltip: 'Save User',
      onClick: (event, rowData) => {
        // Do save operation
      }
    }
  ]}
/>

If possible, how can I separate "Save" and "User" into separate lines?

So far, I tried the following in Chrome 89 in vain:
tooltip: 'Save\nUser'
tooltip: 'Save\rUser'
tooltip: 'Save & # 0 1 3 ; User' (no spaces)

Thanks!
- Sebastian

**Comment by ceafive** [comment]
@sstolzenberg The tooltip property accepts a Node element so you can do this

`  const Tooltip = () => {
    return (
      <div>
        <p>Hello</p>
        <p>Bye</p>
      </div>
    );
  };`

and then use it like this. 
`
{
              icon: "visibility",
              tooltip: <Tooltip />,
              iconProps: {
                color: "secondary",
              },
              onClick(e, row) {
              // do something
              },
            },
`

You can do anything you want in the Tooltip component

**Comment by sstolzenberg** [comment]
ah great, thanks @ceafive !

**Comment by jcatpk** [comment]
@ceafive @sstolzenberg If I understand correctly, setting `tooltip` with a Node element is technically possible, it also will result in a warning message like
`Warning: Failed prop type: Invalid prop `actions[0]` supplied to `MaterialTable`, expected one of type [function, string].`

This happens because `tooltip` is defined as string type in props definition
