### ISSUE TITLE
Remote Data with local sorting and filtering

### ISSUE THREAD

**Issue by lclankyo** [mbrn/material-table#3032]
Greetings, I want to be able to do server side pagination fetching, but keep the normal behavior of the table. To clarify, I want the global search filter, the column filters, and sorting to behave normally, but I want to load the data set via remote data.

I was reading the documentation, and it seems they want us to define the filtering, sorting ourselves:
```
material-table' remote data feature allows the user to implement a custom data fetching function. Using this functionality, searching, filtering, sorting and paging are ignored by material-table and have to be manually implemented.
```

Is there an easy way to enable remote querying, but leave the filtering and sorting alone? 

I saw another post saying that I can filter the data of my promise manually. Is this the only way?
-- And if this is the only way:
1) How do I disable the fetching when I change the filtering value or sort?
2) Is there a place that specifies how this filtering is normally handled by material-table so that I can copy the behavior?

Thank you.

**Comment by chuck-durst** [comment]
Hi,

In case you haven't found an answer to your question yet, I think I can give you some hints. 

Technically it is possible to use external data while keeping the native filter and search functionalities. However I don't think it's a good practice if your table contains several pages, because the search or sorting will only be done on the results of the current local page.

For example, if your dataset contains a "name" column with values like "Arthur", "Bob" and "Carl" but your table displays only two results per page, when you do an ascending alphabetical sort, you will see "Bob" and then "Arthur" displayed in order because "Carl" is not on the current page. This is usually not the expected result.

An alternative would be to pre-fetch all the data from your table and add a local pagination on top of it. But depending on the quantity of data to be displayed in your table, this solution might not be optimal. 
Personally, when I use this library to display remote data, I prefer to let my API manage filters, sorting and searching.

For the rest, I think you'll find all the information you need on the documentation 👇

https://material-table.com/#/docs/features/remote-data

Hope it helps
