### ISSUE TITLE
Display html tag on field

### ISSUE THREAD

**Issue by ewerton-azevedo** [mbrn/material-table#304]
Is there a way to render an HTML tag when displaying field content?

```
 columns={[
                  { title: 'Link', field: 'httpLink'},
                ]}
```

Data from server:  `<a href= 'https://www.google.com' > Google </a> `

The output on the table: `<a href='https://www.google.com'>Google</a>`

Expected: [Google](https://www.google.com)

Is that a way to render HTML tags this way?

**Comment by mbrn** [comment]
You can use custom render feature. 

https://mbrn.github.io/material-table/#/docz-examples-07-example-custom-render

**Comment by aliwasif177** [comment]
Hi, 
I am facing problem in image rendrering when I tried to edit a cell with editable option .   I have rendered all html using document in given link. At first it works fine but when I click on edit icon It throws error like invalid json data. I think it is due to the table re-rendering at which table realizes it's html and throws error on data .
