### ISSUE TITLE
How to disable react-beautiful-dnd warning?

### ISSUE THREAD

**Issue by weilinzung** [mbrn/material-table#3073]
![Screen Shot 2021-12-06 at 11 28 30 AM](https://user-images.githubusercontent.com/7368063/144884802-f9c639ab-1f1b-4bb5-af7f-9c8d69121373.png)

I am using this for Figma plugin, so the doctype isn't really needed in this case.

Thanks!

**Comment by ontanj** [comment]
There should be a way to do this, but the information on how is missing. [docs/guides/doctype.md](https://github.com/atlassian/react-beautiful-dnd/blob/d77908e2c31a081aef766c0f624994bbbc7edb9c/docs/guides/doctype.md)

By looking in the code the only way I found was setting `window["__react-beautiful-dnd-disable-dev-warnings"] = true;`, which disables _all_ warnings. This is fine for me since I don't use this library directly.
