### ISSUE TITLE
page crash when data is more in tree view

### ISSUE THREAD

**Issue by bchandak** [mbrn/material-table#3165]
Describe the bug
When there is 2000+ in the child the table freezes for a while to render the rows.

Expected behavior
Even a long list of rows should render properly

**Comment by NassimBeniken** [comment]
I have the same issue.

While using tree data, if children are large dataset, the page crash or the table freezes during a long time

**Comment by ibr4qr** [comment]
it does crash or there is a stack overflow for recursively infinite function calls?
If not, there's some sort of error in the browser console??

**Comment by NassimBeniken** [comment]
> it does crash or there is a stack overflow for recursively infinite function calls?
> 
> If not, there's some sort of error in the browser console??

The thing is that when children is an array with a large amount of data, the page freezes for a while and finally displays the children (on tree expand) after more than a minute in my case (one parent with 3600+ children)

Even after the children are all displayed, the page is very slow, and if you have filters, it also takes a lot of time to filter the rows

The problem here is that there is too much data in parent and it's difficult to display all these data

Pagination doesn't work because it applies pagination only on parent (children are not considered as row of the table)
