### ISSUE TITLE
onSelectionChange and setState not working well

### ISSUE THREAD

**Issue by kyapwc** [mbrn/material-table#469]
**Describe the bug**
Checkboxes do not get selected when `setState` is used alongside `onSelectionChange`. Currently using version 1.32.0

**To Reproduce**
1. Create a table and set a `onSelectionChange()`
2. do a `this.setState()` with the data taken from `onSelectionChange`
3. Checkboxes does not get checked
4. Example:
```
<MaterialTable
  columns={[...]}
  data={...}
  onSelectionChange={(data) => this.setState({ selectedOrders: data })}
  options={{...}}
/>
```

**Expected behavior**
Checkboxes to be checked and state is set.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox, Google Chrome
 - Version: Firefox Quantum Version 66.0.3 (64 bit), Google Chrome Version 73.0.3683.103 (64 bit)

**Comment by kyapwc** [comment]
Nevermind this issue, realized it was due to re-rendering of the component that made it not checked.

**Comment by uplsaurabhA** [comment]
How did you solve this issue?I am calling a function inside onSelectionChange inside which i am changing state. I there another way?

**Comment by kyapwc** [comment]
Hey @uplsaurabhA, there is a way, which is to do it like this:
```
handleCheckboxClick = (rowData) => {
  this.setState({
    selectedItems: {
      ...rowData,
      tableData: {
        checked: true,
      }
    }
  })
}
```

You can override the checkbox to be checked using `material-table`

**Comment by mbrn** [comment]
With latest version you can call functions of material-table with tableRef. Did you check it?

**Comment by DeanDiDi** [comment]
In case anybody still has trouble fixing this issue. You can either:
1. Add shouldComponentUpdate check to force the material-table not to be re-rendered, or
2. Change the data array which you feed into the material-table, please refer to #96 for detailed implementation

**Comment by shasanka** [comment]
I am trying to change state after onSelectionChange , but after changing the state , selection on the table is not shown in the UI , field is selected but its not showing in the UI.
Please help

**Comment by tonypee** [comment]
as @DeanDiDi said, you should either cause the table to re-render (shouldComponentUpdate) or explicitly tell the row that it is selected  - look at #96

**Comment by Tellisense** [comment]
Instead of using useState, another way is to use useRef.   useRef will not cause a re-render so it's independent of the component lifecycle, and in this case will cause the checkboxes to function normally, a simple fix, hopefully this helps someone. 

 const selectedRow = React.useRef([]);

 const handleClick = rows => {
    selectedRow.current = rows;
    console.log(`selectedRow: `, selectedRow.current);
  };


//inside the material-table 
    onSelectionChange={rows => {
                        handleClick(rows);
                      }}

**Comment by amisoliman** [comment]
Is it possible to select all rows on current page?

**Comment by xiaochenzhang** [comment]
hi @Tellisense , or other people who may help, 

besides `useRef`, are there other ways to change the state of another object when `onSelectionChange`? I am facing an issue, which is whenever the table selection is changed, I want to toggle the disabled state of a button based on the selection. I have tried with useRef like below, but since the useRef does not trigger re-render, the button disabled style is not changed:

```
  const confirmSelectionBtn = React.useRef();
  
  const handleTableSelectionChange = (rows) => {
    if (confirmSelectionBtn && confirmSelectionBtn.current) {
      confirmSelectionBtn.current.disabled = rows.length === 0;
    }
  };
```

I think setState should be possible inside the `onSelectionChange` event, so I don't understand why material table does not support this. Or maybe I just missed how to make it happen?

**Comment by aiavci** [comment]
Another fix is to make sure the state update resulting from the `onSelectionChange` call updates the value provided to the `data` property passed into MaterialTable. 

Here's a sample:

```
<MaterialTable
    data={this.state.data}
    onSelectionChange={(rows, rowsData) => {
        const updatedData = data?.map((t) => {
              if (t._id === rowData._id) {
                 return {
                     ...t,
                     tableData: rowData.tableData,
                  };
               } else {
                    return t;
               }
          });
          
          this.setState({
              data: updatedData,
              selectedRows: rows,
           });
    })
/>
```

**Comment by h0rak** [comment]
> With latest version you can call functions of material-table with tableRef. Did you check it?

I have four tabs which each use their own table. If I select boxes in one table, switch tabs, then switch back, the rows are still selected. If I hit my delete all button which is in the toolbar on select, it doesn't work.

My question is: Can I just set up my tables to get deselected when I change tabs so that when I come back to that table everything is unchecked and reset? If so, should I use useState or tableRef?

**Comment by felipehimself** [comment]
I was facing the same issue and found out the `useState` name must be the same as MRT_RowSelectionState, after I changed it, it works:

If you are facing this issue when you select the checkbox and the UI doesn't update write your state like this (it's the same name they use in the docs, but I guess it's not helpful because they don't make it clear):

```
// the state must be written like this since 
// MRT uses under the hood the state name to match the type MRT_RowSelectionState
  
 const [rowSelection, setRowSelection] = useState<MRT_RowSelectionState>({});
```

Just for your reference and to show what I meant above `MRT_RowSelectionState` is:

```
export interface RowSelectionTableState {
    rowSelection: RowSelectionState;
}

```
