### ISSUE TITLE
Nested expanded rows collapses on selection

### ISSUE THREAD

**Issue by ozandogrultan** [mbrn/material-table#498]
**Describe the bug**
Related issue #443 . Still not fixed for nested rows that have depth more than 1.

**To Reproduce**
1. Render a table that is nested more than 1 level
2. Select any nested child or parent row

**Expected behavior**
Row collapse/expand not triggered by selection.

**Screenshots**
![Apr-22-2019 18-58-15](https://user-images.githubusercontent.com/5598573/56509824-ac982b00-6530-11e9-9e41-343843f1a17c.gif)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 1.32.0

**Comment by mbrn** [comment]
Please upgrade to 1.34.0

**Comment by GienekGenin** [comment]
@mbrn Still not fixed for nested rows that have depth more than 1.

![BitStreamGoogleChrome20190](https://user-images.githubusercontent.com/27743401/57362073-450feb80-717e-11e9-8a25-00afd604182e.gif)

Desktop:
OS: Windows 10
Browser: Chrome
Version `"material-table": "^1.36.1"`

**Comment by mbrn** [comment]
Hi @GienekGenin,

I will look at this asap.

**Comment by theodore-koch** [comment]
Was this ever resolved?

**Comment by benjaminvdb** [comment]
![select_collapse](https://user-images.githubusercontent.com/8875786/62302755-2d918780-b47b-11e9-8a30-4de02f1a1e2f.gif)

I'm on version 1.41.0 and I'm having the same issue: the tree collapses whenever I select a row.

**Comment by v1nns** [comment]
Up

**Comment by raph90** [comment]
Yikes we're all in the same boat... :(

**Comment by emrekara37** [comment]
Hi , i am working on it 
We will fixed it asap.

**Comment by ruthwe** [comment]
any news?

**Comment by lsansaa** [comment]
Not sure if is related, but this happens with actions buttons if do something like showing a modal/dialog.

Is there a way to get the on click event of the expand button? Got an idea of how quick fix this, saving on a state the isTreeExpanded attribute of each row and then using it to render the row. The onTreeExpandChange event won't do the thing since it gets trigger after the row is rendered, not after clicking the button (Already try it with this one)

**Comment by v1nns** [comment]
Any update about it?
