### ISSUE TITLE
Mutliple Sorting

### ISSUE THREAD

**Issue by kadirguloglu** [mbrn/material-table#541]
How can i multiple sorting ?

**Comment by mbrn** [comment]
Hi @kadirguloglu ,

Currently, material-table does not support for multiple sorting. I am planning to add it for future releases. But now i am working on bugs and performance issues firstly.

**Comment by cooperate** [comment]
By multiple sorting is this referring to a secondary sort option?

Is there a way for me to reference a secondary sort toggle?

So i sort column A in this way

```
Col A | Col B
10        E
10         D
10         C
12         A
13         B
13         Z 
13         A
```

And then enable "secondary sort" and secondary sort Col B in this way

```
Col A | Col B
10        C
10        D
10        E
12        A
13        A
13        B
13        Z  
```

As far as I can tell customSort cannot accommodate this because it only pertains to values from rows within the same column.

**Comment by cooperate** [comment]
@mbrn

**Comment by Slavik89** [comment]
Could you give link to it?

**Comment by Shaquu** [comment]
Is it possible to get that feature?
