### ISSUE TITLE
Need to be able to disable the confirm button when editing

### ISSUE THREAD

**Issue by jakeleventhal** [mbrn/material-table#682]
**Is your feature request related to a problem? Please describe.**
When editing, there needs to be a way to disable the confirm button - for instance if you don't want the user to input something empty - or meet some other criteria - for a certain column

**Describe the solution you'd like**
A function to provide the conditions in which the confirm button should be disabled

**Comment by aleccaputo** [comment]
Any updates on this?

**Comment by jakeleventhal** [comment]
not stale!

**Comment by jakeleventhal** [comment]
not stale

**Comment by jakeleventhal** [comment]
not stale

**Comment by weagertron** [comment]
You can use the `validate` function for the column in question e.g.

```
...other column props,
validate: rowData => {
    return rowData.username.trim().length > 0
}
```

In this instance, if the `username` field's length is 0 then the save button will be disabled.
Essentially if the `validate` function returns `true` the save button is enabled, otherwise, it is disabled.

NOTE: This can sometimes cause issues on new rows as the `username` field will likely be undefined. Make sure to do some null checks in here too
