### ISSUE TITLE
Thin line at the bottom of the table

### ISSUE THREAD

**Issue by AntoniusGolly** [mbrn/material-table#695]
**Describe the bug**
All `<td>` elements have a thin bottom line due to
```
.MuiTableCell-root{
   border-bottom: 1px solid rgba(224, 224, 224, 1);
}
```

This will cause a thin line under the table as the table navigation is contained in a `<td>` aswell. Especially with dark backgrounds this thin line is quite obvious and not nice. Currently, I use a css hack to hide the bottom line.

**To Reproduce**
See all examples and increase the border radius of table wrapper to e.g. 40px.

**Screenshots**
![image](https://user-images.githubusercontent.com/3856505/59161339-d6f27780-8ae1-11e9-9511-e83def7f5f4e.png)
The border radius of the wrapper is artificially increased to make the problem obvious.

**Comment by diegosps** [comment]
I just update my material-table from version 1.36.4 to the latest version and came across this problem.
The class `MuiTableCell-footer` now has a property `line-height: 1.3125rem;` instead of `border-bottom: 0;`
Adding the missing property fixes the issue. 

The problems is: I don't know how to do this. There is no `options.footerStyle` available.
