### ISSUE TITLE
Reset table state on data change

### ISSUE THREAD

**Issue by makr11** [mbrn/material-table#751]
When editable and add data are true, that state stays even when table data is changed. Also, pagination is not set to 0, but it stays on previously selected page.

Is it possible to call onEditingCanceled when data props are changed and reset page to 0.

![upgrade](https://user-images.githubusercontent.com/31960173/60016111-85232300-9685-11e9-93b1-4500d76bf489.gif)

**Comment by foramshah1112** [comment]
I have a similar issue. I need to clear my state on AddRowCancelled & onEditCancelled. Is there any way to access the onClick event of add, edit, clear icons of editable attribute?

**Comment by hGica** [comment]
To hack your way into getting onEditCanceled and AddRowCancelled I've added an example. Mode (mode,props) differs for onEditCancelled and AddRowCancelled. I've added my own code to clear validation errors and also added a state parameter (modifiedHook) to not keep adding stuff  to the event each time the method is triggered.

 <MaterialTable
              icons={tableIcons}
              tableRef={(props)=>{
                console.log('hooks',props);
                if(props&&this.state.modifiedHook!==true)
                {
                let cancel=props.onEditingCanceled;
                props.onEditingCanceled=(mode,props)=>{
                  this.setState({error:{},modifiedHook:true});
                  cancel(mode,props);
                };
              }}}
              title="Custom Edit Component Preview"

**Comment by J12ATA** [comment]
@hGica Your code snippet worked wonders for when I needed to access onEditCancelled. Is there a way to get access to the onClick event of the add icon? Thanks in advance.

**Comment by hGica** [comment]
@J12ATA 

<MaterialTable
.
.
.
components={{
Action:props=>{
console.log('action props',props);
if(props.action.tooltip==="Add")
{
var add=props.action.onClick;
let addNew=()=>{
this.setState({error:{}});
add();
};
props.action.onClick=addNew;
}
return( <MTableAction {...props}/>)
}
}}

Override actions so when the action with tooltip "Add" instead of sending default onClick as prop, add a function that executes what you want and then executes the onClick. I've also tried this for onEditingApproved and canceled but overriding the editable component causes other issues, like components loosing focus on each key press.

**Comment by hGica** [comment]
@J12ATA
you could also add a small fix for onEditCanceled. Since state is managed asynchronously this.state.modifiedHook does not get modified immediately so you can end up adding the same function more times, so as a solution I propose

if(props&&this.state.modifiedHook!==true&&props.onEditingCanceled.length<3)
{
let cancel=props.onEditingCanceled;
props.onEditingCanceled=(mode,props,test)=>{
console.log('canceled');
this.setState({error:{},modifiedHook:true});
cancel(mode,props);
};
....
by adding a new parameter to the function you are able to test that the function has changed and it now has 3 parameters instead of 2.
