### ISSUE TITLE
Add a handler `onRowEdit` and `onRowEditCancel`

### ISSUE THREAD

**Issue by AntoniusGolly** [mbrn/material-table#786]
For when `editable` objects are provided...

**Is your feature request related to a problem? Please describe.**
I check for errors when validating input data on editing or adding new items. Those errors I want to clear when the editing is canceled. 

**Describe the solution you'd like**
There is already some nice handlers as `onOrderChange` or `onRowClick`. I would like to have an additional handler `onRowEdit` when editing is started and `onRowEditCancel` when the X is pressed in editing mode. 

**Additional context**
Also, I think it makes great sense to have a handler for when the `detailPanel` is opened/closed.

**Comment by hGica** [comment]
I am also searching for a way to do this. I also couldn't manage to successfully override editrow component to get the functionality as there is no documentation on how to do this.

**Comment by waisbek** [comment]
It's a great idea, I also need identify when the user is editing.

**Comment by hGica** [comment]
@waisbek  see my answers on https://github.com/mbrn/material-table/issues/751 though I wasn't able to get access to is editing

**Comment by CycoPH** [comment]
Internally there is the 'onEditingCanceled' event.  It just has to be exposed to the outside.
This would make external messaging way easier if we know when cancel was pressed.

**Comment by Rombusevil** [comment]
I've stumbled upon this issue due to needing functionality to handle a user message when quitting the page with unsaved data. I've made the PR providing a callback that will be called with a boolean indicating a "isEditing" status. 
You can try it out installing it like this  `npm install git://github.com/Rombusevil/material-table.git#onEditingStatusChange-build --save`
