### ISSUE TITLE
how to reset page Index？[Pagination]

### ISSUE THREAD

**Issue by Kelier** [mbrn/material-table#955]
In the first operation, I went to the page index 2. At this time, I clicked the button to reload a batch of new data, but the page number below was not set to 1.

**Comment by ggalabarof** [comment]
same problem here

**Comment by AbelRodriguezGumiel** [comment]
How can I change the current page programmatically?

**Comment by lkostrowski** [comment]
I had this issue and I hacked it around like this:

```
const tableRef = useRef<any>();

	const hackyResetPage = () => {
         // null is empty event, 0 is page index
		tableRef.current?.onChangePage(null, 0);
	};

	return (
		<MaterialTable<Account>
			tableRef={tableRef as any}
			onSearchChange={hackyResetPage}
			onFilterChange={hackyResetPage}
		/>
	);
```

@mbrn I can open a PR (if doesn't exist yet) to add this feature, which will be:
1. `resetPaginationOnFilter` option or something like this, which will set index 0 while searched or paginated.
2. Add public method to set pagination instead of calling an event

**Comment by afitzgerald** [comment]
I just ran across this as well.  I would like to explicitly set the page (usually to 0) on changing the data.  Having it always stay on a random page is messy.

**Comment by Cristy94** [comment]
Same issue, in my case the entire React application crashes because the page is out of bounds after changing filtering options.
